
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <title> | Hexo</title>
    <meta name="author" content="John Doe" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <link rel="icon" href="/images/avatar.jpg" />
    <link rel="preconnect" href="https://s4.zstatic.net" />
<script src="https://s4.zstatic.net/ajax/libs/vue/3.3.7/vue.global.prod.min.js"></script>
<link rel="stylesheet" href="https://s4.zstatic.net/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
<link rel="preconnect" href="https://fonts.googleapis.cn" />
<link rel="preconnect" href="https://fonts.gstatic.cn" crossorigin />
<link
    rel="stylesheet"
    href="https://fonts.googleapis.cn/css2?family=Fira+Code:wght@400;500;600;700&family=Lexend:wght@400;500;600;700;800;900&family=Noto+Sans+SC:wght@400;500;600;700;800;900&display=swap"
/>
<script> const mixins = {}; </script>

<script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=default"></script>


<script src="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://s4.zstatic.net/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
<link
    rel="stylesheet"
    href="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/styles/github.min.css"
/>
<script src="/js/lib/highlight.js"></script>



<script src="/js/lib/preview.js"></script>









<link rel="stylesheet" href="/css/main.css" />

<meta name="generator" content="Hexo 7.3.0"></head>
<body>
    <div id="layout">
        <transition name="fade">
            <div id="loading" v-show="loading">
                <div id="loading-circle">
                    <h2>LOADING</h2>
                    <p>加载过慢请开启缓存 浏览器默认开启</p>
                    <img src="/images/loading.gif" />
                </div>
            </div>
        </transition>
        <div id="menu" :class="{ hidden: hiddenMenu, 'menu-color': menuColor}">
    <nav id="desktop-menu">
        <a class="title" href="/">
            <span>HEXO</span>
        </a>
        
        <a href="/">
            <i class="fa-solid fa-house fa-fw"></i>
            <span>&ensp;Home</span>
        </a>
        
        <a href="/about">
            <i class="fa-solid fa-id-card fa-fw"></i>
            <span>&ensp;About</span>
        </a>
        
        <a href="/archives">
            <i class="fa-solid fa-box-archive fa-fw"></i>
            <span>&ensp;Archives</span>
        </a>
        
        <a href="/categories">
            <i class="fa-solid fa-bookmark fa-fw"></i>
            <span>&ensp;Categories</span>
        </a>
        
        <a href="/tags">
            <i class="fa-solid fa-tags fa-fw"></i>
            <span>&ensp;Tags</span>
        </a>
        
    </nav>
    <nav id="mobile-menu">
        <div class="title" @click="showMenuItems = !showMenuItems">
            <i class="fa-solid fa-bars fa-fw"></i>
            <span>&emsp;HEXO</span>
        </div>
        <transition name="slide">
            <div class="items" v-show="showMenuItems">
                
                <a href="/">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-house fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Home</div>
                    </div>
                </a>
                
                <a href="/about">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-id-card fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">About</div>
                    </div>
                </a>
                
                <a href="/archives">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-box-archive fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Archives</div>
                    </div>
                </a>
                
                <a href="/categories">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-bookmark fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Categories</div>
                    </div>
                </a>
                
                <a href="/tags">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-tags fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Tags</div>
                    </div>
                </a>
                
            </div>
        </transition>
    </nav>
</div>
<transition name="fade">
    <div id="menu-curtain" @click="showMenuItems = !showMenuItems" v-show="showMenuItems"></div>
</transition>

        <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
            <div class="article">
    <div>
        <h1></h1>
    </div>
    <div class="info">
        <span class="date">
            <span class="icon">
                <i class="fa-solid fa-calendar fa-fw"></i>
            </span>
            2024/12/28
        </span>
        
        
    </div>
    
    <div class="content" v-pre>
        <h1 id="概念设计"><a href="#概念设计" class="headerlink" title="概念设计"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Conceptual_Design_html">概念设计</a></h1><p>本章讨论用于在族文档中创建复杂几何图形的Revit API的概念设计功能。通过添加新对象（点和通过这些点的样条曲线）来支持形状制作。可以分割、填充图案和嵌板化生成的曲面，以创建具有持久参数关系的可构建形状。</p>
<p>本节中的页面</p>
<ul>
<li>点和曲线对象</li>
<li>形状</li>
<li>曲面的几何化</li>
<li>自适应构件</li>
<li>创建.addin清单文件</li>
</ul>
<h2 id="点和曲线对象"><a href="#点和曲线对象" class="headerlink" title="点和曲线对象"></a>点和曲线对象</h2><p>参照点是在概念设计环境的XYZ工作空间中指定位置的元素。可以创建参照点来设计和打印直线、样条曲线和形状。可以将ReferencePoint添加到ReferencePointArray，然后用于创建CurveByPoints，而CurveByPoints又可用于创建形状。</p>
<p>下面的示例演示如何创建CurveByPoints对象。请参见下一节中的“创建放样形状”示例，了解如何从多个CurveByPoints对象创建形状。</p>
<p>代码区域14-1：创建新的CurveByPoints</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">//体量中创建</span></span><br><span class="line">ReferencePointArray rpa = <span class="keyword">new</span> ReferencePointArray();</span><br><span class="line"></span><br><span class="line">XYZ xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">ReferencePoint rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">30</span>, <span class="number">10</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">60</span>, <span class="number">0</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">30</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">150</span>, <span class="number">0</span>);</span><br><span class="line">rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">CurveByPoints curve = document.FamilyCreate.NewCurveByPoints(rpa);</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-91A84A22-3B88-45F4-B7CE-8D75F685A95A-low.png"></p>
<p>图54：CurveByPoints曲线</p>
<p>参照点可以基于XYZ坐标创建，如上例所示，也可以相对于其他几何图元创建，以便当参照几何图元更改时，这些点会移动。这些点使用PointElementReference类的子类创建。这些子类是：</p>
<ul>
<li>PointOnEdge</li>
<li>PointOnEdgeEdgeIntersection</li>
<li>PointOnEdgeFaceIntersection</li>
<li>PointOnFace</li>
<li>PointOnPlane</li>
</ul>
<p>例如，上一个示例中的最后两行代码在CurveByPoints的中间创建了一个参考点。</p>
<p>可以使用模型线或参照线创建形状。模型线在创建过程中由形状“使用”，不再作为单独的图元存在。另一方面，参照线在形状创建后仍然存在，如果移动它们，可能会改变形状。虽然API没有ReferenceLine类，但可以使用ModelCurve.ChangeToReferenceLine（）方法将模型线更改为参考线。</p>
<p>代码区域14-2：使用参照线创建形状</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">//demo失败（报错，无效操作）</span></span><br><span class="line"><span class="function"><span class="keyword">private</span> FormArray <span class="title">CreateRevolveForm</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    FormArray revolveForms = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create one profile</span></span><br><span class="line">    ReferenceArray ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">    XYZ ptA = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    XYZ ptB = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    Line line = Line.CreateBound(ptA, ptB);</span><br><span class="line">    ModelCurve modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">100</span>, <span class="number">10</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">100</span>, <span class="number">100</span>, <span class="number">10</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create axis for revolve form</span></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">-5</span>, <span class="number">0</span>, <span class="number">10</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">-5</span>, <span class="number">10</span>, <span class="number">10</span>);</span><br><span class="line">    ModelCurve axis = MakeLine(document, ptA, ptB);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// make axis a Reference Line</span></span><br><span class="line">    axis.ChangeToReferenceLine();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Typically this operation produces only a single form, </span></span><br><span class="line">    <span class="comment">// but some combinations of arguments will create multiple froms from a single profile.</span></span><br><span class="line">    revolveForms = document.FamilyCreate.NewRevolveForms(<span class="literal">true</span>, ref_ar, axis.GeometryCurve.Reference, <span class="number">0</span>, Math.PI / <span class="number">4</span>);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> revolveForms;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> ModelCurve <span class="title">MakeLine</span>(<span class="params">Document doc, XYZ ptA, XYZ ptB</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = doc.Application;</span><br><span class="line">    <span class="comment">// Create plane by the points</span></span><br><span class="line">    Line line = Line.CreateBound(ptA, ptB);</span><br><span class="line">    XYZ norm = ptA.CrossProduct(ptB);</span><br><span class="line">    <span class="keyword">if</span> (norm.IsZeroLength()) norm = XYZ.BasisZ;</span><br><span class="line">    Plane plane = Plane.CreateByNormalAndOrigin(norm, ptB);</span><br><span class="line">    SketchPlane skplane = SketchPlane.Create(doc, plane);</span><br><span class="line">    <span class="comment">// Create line here</span></span><br><span class="line">    ModelCurve modelcurve = doc.FamilyCreate.NewModelCurve(line, skplane);</span><br><span class="line">    <span class="keyword">return</span> modelcurve;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-F5F29826-D2EA-4007-8C3F-8F30975261C4-low.png"></p>
<p>图55：生成的Revolve表单</p>
<h2 id="形状"><a href="#形状" class="headerlink" title="形状"></a>形状</h2><h3 id="创建形状"><a href="#创建形状" class="headerlink" title="创建形状"></a>创建形状</h3><p>与族创建类似，概念设计环境提供了创建新形状的功能。可以创建以下类型的形状：拉伸、旋转、放样、放样融合、放样和曲面形状。体量族不使用族创建中使用的“混合”、“拉伸”、“旋转”、“放样”和“放样融合”类，而是将“形状”类用于所有类型的形状。</p>
<p>拉伸形状是从平面的闭合曲线回路创建的。旋转形状是根据轮廓和与轮廓在同一平面上的直线创建的，轮廓是围绕其旋转形状以创建三维形状的轴。放样形状是从沿沿着平面路径放样的二维轮廓创建的。放样融合是从多个轮廓创建的，每个轮廓都是平面的，沿沿着单个曲线放样。放样形状由位于不同平面上的两个或多个截面轮廓创建。单个曲面形状是从轮廓创建的，类似于拉伸，但不指定高度。</p>
<p>下面的示例创建一个简单的拉伸形状。请注意，由于用于创建形状的ModelCurves不会转换为参照线，因此它们将由生成的形状使用。</p>
<p>代码区域14-3：创建拉伸形状</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Form <span class="title">CreateExtrusionForm</span>(<span class="params">Autodesk.Revit.DB.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Form extrusionForm = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create one profile</span></span><br><span class="line">    ReferenceArray ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">    XYZ ptA = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ ptB = <span class="keyword">new</span> XYZ(<span class="number">90</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    ModelCurve modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">90</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">90</span>, <span class="number">0</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    ptA = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">90</span>, <span class="number">0</span>);</span><br><span class="line">    ptB = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">    modelcurve = MakeLine(document, ptA, ptB);</span><br><span class="line">    ref_ar.Append(modelcurve.GeometryCurve.Reference);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// The extrusion form direction</span></span><br><span class="line">    XYZ direction = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">50</span>);</span><br><span class="line"></span><br><span class="line">    extrusionForm = document.FamilyCreate.NewExtrusionForm(<span class="literal">true</span>, ref_ar, direction);</span><br><span class="line"></span><br><span class="line">    <span class="built_in">int</span> profileCount = extrusionForm.ProfileCount;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> extrusionForm;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">public</span> ModelCurve <span class="title">MakeLine</span>(<span class="params">Document doc, XYZ ptA, XYZ ptB</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = doc.Application;</span><br><span class="line">    <span class="comment">// Create plane by the points</span></span><br><span class="line">    Line line = Line.CreateBound(ptA, ptB);</span><br><span class="line">    XYZ norm = ptA.CrossProduct(ptB);</span><br><span class="line">    <span class="keyword">if</span> (norm.IsZeroLength()) norm = XYZ.BasisZ;</span><br><span class="line">    Plane plane = Plane.CreateByNormalAndOrigin(norm, ptB);</span><br><span class="line">    SketchPlane skplane = SketchPlane.Create(doc, plane);</span><br><span class="line">    <span class="comment">// Create line here</span></span><br><span class="line">    ModelCurve modelcurve = doc.FamilyCreate.NewModelCurve(line, skplane);</span><br><span class="line">    <span class="keyword">return</span> modelcurve;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-ACA912B3-A871-4886-8600-A95C293FB2D5-low.png"></p>
<p>图56：所得拉伸形状</p>
<p>下面的示例显示如何使用一系列CurveByPoints对象创建放样形状。</p>
<p>代码区域14-4：创建放样形状</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Form <span class="title">CreateLoftForm</span>(<span class="params">Autodesk.Revit.Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Form loftForm = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">        ReferencePointArray rpa = <span class="keyword">new</span> ReferencePointArray();</span><br><span class="line">        ReferenceArrayArray ref_ar_ar = <span class="keyword">new</span> ReferenceArrayArray();</span><br><span class="line">        ReferenceArray ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line">        ReferencePoint rp = <span class="literal">null</span>;</span><br><span class="line">        XYZ xyz = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make first profile curve for loft</span></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">50</span>, <span class="number">10</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">0</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        CurveByPoints cbp = document.FamilyCreate.NewCurveByPoints(rpa);</span><br><span class="line">        ref_ar.Append(cbp.GeometryCurve.Reference);</span><br><span class="line">        ref_ar_ar.Append(ref_ar);</span><br><span class="line">        rpa.Clear();</span><br><span class="line">        ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make second profile curve for loft</span></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">50</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">50</span>, <span class="number">50</span>, <span class="number">30</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">50</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        cbp = document.FamilyCreate.NewCurveByPoints(rpa);</span><br><span class="line">        ref_ar.Append(cbp.GeometryCurve.Reference);</span><br><span class="line">        ref_ar_ar.Append(ref_ar);</span><br><span class="line">        rpa.Clear();</span><br><span class="line">        ref_ar = <span class="keyword">new</span> ReferenceArray();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// make third profile curve for loft</span></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">75</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">75</span>, <span class="number">50</span>, <span class="number">5</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        xyz = document.Application.Create.NewXYZ(<span class="number">75</span>, <span class="number">100</span>, <span class="number">0</span>);</span><br><span class="line">        rp = document.FamilyCreate.NewReferencePoint(xyz);</span><br><span class="line">        rpa.Append(rp);</span><br><span class="line"></span><br><span class="line">        cbp = document.FamilyCreate.NewCurveByPoints(rpa);</span><br><span class="line">        ref_ar.Append(cbp.GeometryCurve.Reference);</span><br><span class="line">        ref_ar_ar.Append(ref_ar);</span><br><span class="line"></span><br><span class="line">        loftForm = document.FamilyCreate.NewLoftForm(<span class="literal">true</span>, ref_ar_ar);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> loftForm;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8F7F53FC-51B6-4547-86C4-709C11B72FCA-low.png"></p>
<p>图57：生成的放样形状</p>
<h3 id="形状修改"><a href="#形状修改" class="headerlink" title="形状修改"></a>形状修改</h3><p>一旦创建，可以通过改变形状的子元素（即面、边、曲线或顶点）或整个轮廓来修改形状。修改表单的方法包括：</p>
<ul>
<li>AddEdge</li>
<li>AddProfile</li>
<li>DeleteProfile</li>
<li>DeleteSubElement</li>
<li>MoveProfile </li>
<li>MoveSubElement </li>
<li>RotateProfile</li>
<li>RotateSubElement</li>
<li>ScaleSubElement</li>
</ul>
<p>此外，可以通过添加边或轮廓来修改形状，然后可以使用上面列出的方法进行修改。</p>
<p>下面的示例将给定形状的第一条轮廓曲线移动指定的偏移量。相应的图显示了将此代码应用于上一个示例中的放样形式的结果。</p>
<p>代码区域14-5：移动轮廓</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MoveForm</span>(<span class="params">Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="built_in">int</span> profileCount = form.ProfileCount;</span><br><span class="line">        <span class="keyword">if</span> (form.ProfileCount &gt; <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="built_in">int</span> profileIndex = <span class="number">0</span>;   <span class="comment">// modify the first form only</span></span><br><span class="line">                <span class="keyword">if</span> (form.CanManipulateProfile(profileIndex))</span><br><span class="line">                &#123;</span><br><span class="line">                XYZ offset = <span class="keyword">new</span> XYZ(<span class="number">-25</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">                form.MoveProfile(profileIndex, offset);</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-BCA27D2B-71B9-40CE-A94E-2858C22B8A08-low.png"></p>
<p>图58：修改后的放样形式</p>
<p>下一个示例演示如何移动给定形状的单个顶点。相应的图演示了此代码对前面的拉伸形状示例的影响</p>
<p>代码区域14-6：移动子元素</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MoveSubElement</span>(<span class="params">Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="keyword">if</span> (form.ProfileCount &gt; <span class="number">0</span>)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="built_in">int</span> profileIndex = <span class="number">0</span>;   <span class="comment">// get first profile</span></span><br><span class="line">                ReferenceArray ra = form.get_CurveLoopReferencesOnProfile(profileIndex, <span class="number">0</span>);</span><br><span class="line">                <span class="keyword">foreach</span> (Reference r <span class="keyword">in</span> ra)</span><br><span class="line">                &#123;</span><br><span class="line">                        ReferenceArray ra2 = form.GetControlPoints(r);</span><br><span class="line">                        <span class="keyword">foreach</span> (Reference r2 <span class="keyword">in</span> ra2)</span><br><span class="line">                        &#123;</span><br><span class="line">                                Point vertex = document.GetElement(r2).GetGeometryObjectFromReference(r2) <span class="keyword">as</span> Point;</span><br><span class="line"></span><br><span class="line">                                XYZ offset = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">15</span>, <span class="number">0</span>);</span><br><span class="line">                                form.MoveSubElement(r2, offset);</span><br><span class="line">                                <span class="keyword">break</span>;  <span class="comment">// just move the first point</span></span><br><span class="line">                        &#125;</span><br><span class="line">                &#125;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>图59：修改拉伸的形状</p>
<h2 id="表面的几何化"><a href="#表面的几何化" class="headerlink" title="表面的几何化"></a>表面的几何化</h2><h3 id="分割表面"><a href="#分割表面" class="headerlink" title="分割表面"></a>分割表面</h3><p>形状的面可以用UV网格划分。可以使用DividedSurface.GetReferencesWithDividedSurface（）和DividedSurface.GetDividedSurfaceForReference（）方法（如后续示例所示）访问分割曲面的数据，也可以在形状上创建新的分割曲面，如下所示。</p>
<p>代码区域14-7：划分表面</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">DivideSurface</span>(<span class="params">Document document, Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application application = document.Application;</span><br><span class="line">    Options opt = application.Create.NewGeometryOptions();</span><br><span class="line">    opt.ComputeReferences = <span class="literal">true</span>;</span><br><span class="line"></span><br><span class="line">    Autodesk.Revit.DB.GeometryElement geomElem = form.get_Geometry(opt);</span><br><span class="line">    <span class="keyword">foreach</span> (GeometryObject geomObj <span class="keyword">in</span> geomElem)</span><br><span class="line">    &#123;</span><br><span class="line">        Solid solid = geomObj <span class="keyword">as</span> Solid;</span><br><span class="line">        <span class="keyword">foreach</span> (Face face <span class="keyword">in</span> solid.Faces)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (face.Reference != <span class="literal">null</span>)</span><br><span class="line">            &#123;</span><br><span class="line">                DividedSurface ds = DividedSurface.Create(document,face.Reference);</span><br><span class="line">                <span class="comment">// create a divided surface with fixed number of U and V grid lines</span></span><br><span class="line">                SpacingRule srU = ds.USpacingRule;</span><br><span class="line">                srU.SetLayoutFixedNumber(<span class="number">16</span>, SpacingRuleJustification.Center, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">                SpacingRule srV = ds.VSpacingRule;</span><br><span class="line">                srV.SetLayoutFixedNumber(<span class="number">24</span>, SpacingRuleJustification.Center, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">                <span class="keyword">break</span>;  <span class="comment">// just divide one face of form</span></span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-68B498E3-3756-47BF-8392-1F12F2F8D4ED-low.png"></p>
<p>图60：由UV网格划分的形状面</p>
<p>通过指定DividedSurface的USpacing和VSpacing属性，可以为U和V网格线定义SpacingRule，方法是指定固定的网格数（如上例所示）、网格之间的固定距离或网格之间的最小或最大间距。每个间距规则都需要其他信息，例如对正和网格旋转。</p>
<p>图案化表面</p>
<p>可以对分割的曲面进行阵列。任何内置平铺填充图案都可以应用于分割表面。平铺图案是指定给DividedSurface的ElementType。平铺图案根据UV栅格布局应用于曲面，因此更改DividedSurface的USpacing和VSpacing属性将影响图案化曲面的显示方式。</p>
<p>下面的示例演示如何使用OctagonRotate图案覆盖分割曲面。相应的图显示了将其应用于上一示例中的分割曲面时的外观。注意这个例子还演示了如何在窗体上获取DividedSurface。</p>
<p>代码区域14-8：图案化表面</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">TileSurface</span>(<span class="params">Document document, Form form</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// cover surface with OctagonRotate tile pattern</span></span><br><span class="line">    TilePatterns tilePatterns = document.Settings.TilePatterns;</span><br><span class="line">    <span class="keyword">foreach</span> (Reference r <span class="keyword">in</span> DividedSurface.GetReferencesWithDividedSurfaces(form))</span><br><span class="line">    &#123;</span><br><span class="line">        DividedSurface ds = DividedSurface.GetDividedSurfaceForReference(document, r);</span><br><span class="line">        ds.ChangeTypeId(tilePatterns.GetTilePattern(TilePatternsBuiltIn.OctagonRotate).Id);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>图61：应用于分割表面的平铺图案</p>
<p>除了将内置的平铺填充图案应用于分割表面之外，还可以使用“基于幕墙嵌板填充图案的.rft”样板创建自己的体量嵌板族。然后，可以使用DividedSurface.ChangeTypeId（）方法将这些嵌板族载入体量族并应用于分割曲面。</p>
<p>“族”的下列属性特定于幕墙嵌板族：</p>
<ul>
<li>IsCurtainPanelFamily</li>
<li>CurtainPanelHorizontalSpacing -分隔网格的水平间距</li>
<li>CurtainPanelVerticalSpacing -分隔网格的垂直间距</li>
<li>CurtainPanelTilePattern -平铺图案的选择</li>
</ul>
<p>下面的示例演示如何编辑体量嵌板族，然后将其应用于概念体量文档中的形状。若要运行此示例，请首先使用“Curtain Panel Pattern Based.rft”样板创建一个新的族文档。</p>
<p>代码区域14-9：编辑幕墙嵌板族</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br></pre></td><td class="code"><pre><span class="line">Family family = document.OwnerFamily;</span><br><span class="line"><span class="keyword">if</span> (family.IsCurtainPanelFamily == <span class="literal">true</span> &amp;&amp;</span><br><span class="line">    family.CurtainPanelTilePattern == TilePatternsBuiltIn.Rectangle)</span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// first change spacing of grids in family document</span></span><br><span class="line">    family.CurtainPanelHorizontalSpacing = <span class="number">20</span>;</span><br><span class="line">    family.CurtainPanelVerticalSpacing = <span class="number">30</span>;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// create new points and lines on grid</span></span><br><span class="line">    Autodesk.Revit.ApplicationServices.Application app = document.Application;</span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection collection = collector.OfClass(<span class="keyword">typeof</span>(ReferencePoint)).ToElements();</span><br><span class="line">    <span class="built_in">int</span> ctr = <span class="number">0</span>;</span><br><span class="line">    ReferencePoint rp0 = <span class="literal">null</span>, rp1 = <span class="literal">null</span>, rp2 = <span class="literal">null</span>, rp3 = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (Autodesk.Revit.DB.Element e <span class="keyword">in</span> collection)</span><br><span class="line">    &#123;</span><br><span class="line">        ReferencePoint rp = e <span class="keyword">as</span> ReferencePoint;</span><br><span class="line">        <span class="keyword">switch</span> (ctr)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">0</span>:</span><br><span class="line">                rp0 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">1</span>:</span><br><span class="line">                rp1 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">2</span>:</span><br><span class="line">                rp2 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">            <span class="keyword">case</span> <span class="number">3</span>:</span><br><span class="line">                rp3 = rp;</span><br><span class="line">                <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">        ctr++;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    ReferencePointArray rpAr = <span class="keyword">new</span> ReferencePointArray();</span><br><span class="line">    rpAr.Append(rp0);</span><br><span class="line">    rpAr.Append(rp2);</span><br><span class="line">    CurveByPoints curve1 = document.FamilyCreate.NewCurveByPoints(rpAr);</span><br><span class="line">    PointLocationOnCurve pointLocationOnCurve25 = <span class="keyword">new</span> PointLocationOnCurve(PointOnCurveMeasurementType.NormalizedCurveParameter, <span class="number">0.25</span>, PointOnCurveMeasureFrom.Beginning);</span><br><span class="line">    PointOnEdge poeA = app.Create.NewPointOnEdge(curve1.GeometryCurve.Reference, pointLocationOnCurve25);</span><br><span class="line">    ReferencePoint rpA = document.FamilyCreate.NewReferencePoint(poeA);</span><br><span class="line">    PointLocationOnCurve pointLocationOnCurve75 = <span class="keyword">new</span> PointLocationOnCurve(PointOnCurveMeasurementType.NormalizedCurveParameter, <span class="number">0.75</span>, PointOnCurveMeasureFrom.Beginning);</span><br><span class="line">    PointOnEdge poeB = app.Create.NewPointOnEdge(curve1.GeometryCurve.Reference, pointLocationOnCurve75);</span><br><span class="line">    ReferencePoint rpB = document.FamilyCreate.NewReferencePoint(poeB);</span><br><span class="line"></span><br><span class="line">    rpAr.Clear();</span><br><span class="line">    rpAr.Append(rp1);</span><br><span class="line">    rpAr.Append(rp3);</span><br><span class="line">    CurveByPoints curve2 = document.FamilyCreate.NewCurveByPoints(rpAr);</span><br><span class="line">    PointOnEdge poeC = app.Create.NewPointOnEdge(curve2.GeometryCurve.Reference, pointLocationOnCurve25);</span><br><span class="line">    ReferencePoint rpC = document.FamilyCreate.NewReferencePoint(poeC);</span><br><span class="line">    PointOnEdge poeD = app.Create.NewPointOnEdge(curve2.GeometryCurve.Reference, pointLocationOnCurve75);</span><br><span class="line">    ReferencePoint rpD = document.FamilyCreate.NewReferencePoint(poeD);</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">else</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Please open a curtain family document before calling this command.&quot;</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-8EECE3F0-4C1F-4B31-9133-D3D64676E7FE-low.png"></p>
<p>图62：幕墙嵌板族</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-263500A5-C732-4E47-B9AA-D878AF9E9729-low.png"></p>
<p>图63：指定给分割表面的幕墙嵌板</p>
<h2 id="自适应构件"><a href="#自适应构件" class="headerlink" title="自适应构件"></a>自适应构件</h2><p>自适应组件旨在处理组件需要灵活地适应许多独特的上下文条件的情况。例如，自适应构件可用于通过排列符合用户定义约束的多个构件生成的重复系统中。</p>
<p>下面的代码显示如何将自适应构件族的实例创建到体量族中，并以数学方式设置每个点的位置。</p>
<p>代码区域：创建自适应构件族的实例</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateAdaptiveComponentInstance</span>(<span class="params">Document document, FamilySymbol symbol</span>)</span></span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">// Create a new instance of an adaptive component family</span></span><br><span class="line">            FamilyInstance instance = AdaptiveComponentInstanceUtils.CreateAdaptiveComponentInstance(document, symbol);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Get the placement points of this instance</span></span><br><span class="line">            <span class="keyword">var</span> placePointIds = <span class="keyword">new</span> List&lt;ElementId&gt;();</span><br><span class="line">            placePointIds = AdaptiveComponentInstanceUtils.GetInstancePlacementPointElementRefIds(instance).ToList();</span><br><span class="line">            <span class="built_in">double</span> x = <span class="number">0</span>;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Set the position of each placement point</span></span><br><span class="line">            <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> placePointIds)</span><br><span class="line">            &#123;</span><br><span class="line">                ReferencePoint point = document.GetElement(id) <span class="keyword">as</span> ReferencePoint;</span><br><span class="line">                point.Position = <span class="keyword">new</span> Autodesk.Revit.DB.XYZ(<span class="number">10</span>*x, <span class="number">10</span>*Math.Cos(x), <span class="number">0</span>);</span><br><span class="line">                x += Math.PI / <span class="number">6</span>;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br></pre></td></tr></table></figure>

<p>若要批处理创建自适应组件，可以使用FamilyInstanceCreationData构造函数的重载，该构造函数接受两个参数-FamilySymbol和要初始化自适应实例的XYZ自适应点列表。结合使用Autodesk. Rev. Creation. ItemFactoryBase. NewFamilyInstances 2（）方法（该方法采用FamilyInstanceCreationData对象列表），可以一次添加多个自适应构件。这可能比逐个放置单个自适应组件更有效。</p>
<h2 id="创建-addin清单文件"><a href="#创建-addin清单文件" class="headerlink" title="创建.addin清单文件"></a>创建.addin清单文件</h2><p>HelloWorld.dll文件出现在项目输出目录中。如果要在Revit中调用应用程序，请创建清单文件以将其注册到Revit中。</p>
<p>创建清单文件</p>
<ol>
<li><p>在记事本中创建一个新的文本文件。</p>
</li>
<li><p>增加以下案文：</p>
<p>代码区域30-10：为外部命令创建.addin清单文件</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">&lt;?xml version=<span class="string">&quot;1.0&quot;</span> encoding=<span class="string">&quot;utf-8&quot;</span> standalone=<span class="string">&quot;no&quot;</span>?&gt;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    HelloWorld</span><br><span class="line">    HelloWorld.HelloWorld</span><br><span class="line">    HelloWorld</span><br><span class="line">    Show Hello World.</span><br><span class="line">    AlwaysVisible</span><br><span class="line">    C:\Samples\HelloWorld\HelloWorld\bin\Debug\HelloWorld.dll</span><br><span class="line">    <span class="number">239B</span>D853<span class="number">-36E4</span><span class="number">-461f</span><span class="number">-9171</span>-C5ACEDA4E723</span><br><span class="line">    ADSK</span><br><span class="line">    Autodesk, Inc, www.autodesk.com</span><br></pre></td></tr></table></figure></li>
</ol>
<p>注意：FullClassName包括在项目属性的“应用程序”选项卡上找到的根命名空间。</p>
<p>将文件保存为HelloWorld.addin并将其放在以下位置：</p>
<ul>
<li>C:\ProgramData\Autodesk\Revit\Addins\2018\</li>
</ul>
<p>有关使用清单文件的更多详细信息，请参阅加载项集成。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2>
    </div>
    
    
    
    
    
    
    
</div>

            <footer id="footer">
    <div id="footer-wrap">
        <div>
            &copy;
            2022 - 2024 Hexo
            <span id="footer-icon">
                <i class="fa-solid fa-font-awesome fa-fw"></i>
            </span>
            &commat;John Doe
        </div>
        <div>
            Based on the <a target="_blank" rel="noopener" href="https://hexo.io">Hexo Engine</a> &amp;
            <a target="_blank" rel="noopener" href="https://github.com/theme-particlex/hexo-theme-particlex">ParticleX Theme</a>
        </div>
        
    </div>
</footer>

        </div>
        
        <transition name="fade">
            <div id="preview" ref="preview" v-show="previewShow">
                <img id="preview-content" ref="previewContent" />
            </div>
        </transition>
        
    </div>
    <script src="/js/main.js"></script>
    
    




    
</body>
</html>
