
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <title> | Hexo</title>
    <meta name="author" content="John Doe" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <link rel="icon" href="/images/avatar.jpg" />
    <link rel="preconnect" href="https://s4.zstatic.net" />
<script src="https://s4.zstatic.net/ajax/libs/vue/3.3.7/vue.global.prod.min.js"></script>
<link rel="stylesheet" href="https://s4.zstatic.net/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
<link rel="preconnect" href="https://fonts.googleapis.cn" />
<link rel="preconnect" href="https://fonts.gstatic.cn" crossorigin />
<link
    rel="stylesheet"
    href="https://fonts.googleapis.cn/css2?family=Fira+Code:wght@400;500;600;700&family=Lexend:wght@400;500;600;700;800;900&family=Noto+Sans+SC:wght@400;500;600;700;800;900&display=swap"
/>
<script> const mixins = {}; </script>

<script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=default"></script>


<script src="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://s4.zstatic.net/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
<link
    rel="stylesheet"
    href="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/styles/github.min.css"
/>
<script src="/js/lib/highlight.js"></script>



<script src="/js/lib/preview.js"></script>









<link rel="stylesheet" href="/css/main.css" />

<meta name="generator" content="Hexo 7.3.0"></head>
<body>
    <div id="layout">
        <transition name="fade">
            <div id="loading" v-show="loading">
                <div id="loading-circle">
                    <h2>LOADING</h2>
                    <p>加载过慢请开启缓存 浏览器默认开启</p>
                    <img src="/images/loading.gif" />
                </div>
            </div>
        </transition>
        <div id="menu" :class="{ hidden: hiddenMenu, 'menu-color': menuColor}">
    <nav id="desktop-menu">
        <a class="title" href="/">
            <span>HEXO</span>
        </a>
        
        <a href="/">
            <i class="fa-solid fa-house fa-fw"></i>
            <span>&ensp;Home</span>
        </a>
        
        <a href="/about">
            <i class="fa-solid fa-id-card fa-fw"></i>
            <span>&ensp;About</span>
        </a>
        
        <a href="/archives">
            <i class="fa-solid fa-box-archive fa-fw"></i>
            <span>&ensp;Archives</span>
        </a>
        
        <a href="/categories">
            <i class="fa-solid fa-bookmark fa-fw"></i>
            <span>&ensp;Categories</span>
        </a>
        
        <a href="/tags">
            <i class="fa-solid fa-tags fa-fw"></i>
            <span>&ensp;Tags</span>
        </a>
        
    </nav>
    <nav id="mobile-menu">
        <div class="title" @click="showMenuItems = !showMenuItems">
            <i class="fa-solid fa-bars fa-fw"></i>
            <span>&emsp;HEXO</span>
        </div>
        <transition name="slide">
            <div class="items" v-show="showMenuItems">
                
                <a href="/">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-house fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Home</div>
                    </div>
                </a>
                
                <a href="/about">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-id-card fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">About</div>
                    </div>
                </a>
                
                <a href="/archives">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-box-archive fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Archives</div>
                    </div>
                </a>
                
                <a href="/categories">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-bookmark fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Categories</div>
                    </div>
                </a>
                
                <a href="/tags">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-tags fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Tags</div>
                    </div>
                </a>
                
            </div>
        </transition>
    </nav>
</div>
<transition name="fade">
    <div id="menu-curtain" @click="showMenuItems = !showMenuItems" v-show="showMenuItems"></div>
</transition>

        <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
            <div class="article">
    <div>
        <h1></h1>
    </div>
    <div class="info">
        <span class="date">
            <span class="icon">
                <i class="fa-solid fa-calendar fa-fw"></i>
            </span>
            2024/12/28
        </span>
        
        
    </div>
    
    <div class="content" v-pre>
        <h1 id="楼梯和扶手"><a href="#楼梯和扶手" class="headerlink" title="楼梯和扶手"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Revit_Geometric_Elements_Stairs_and_Railings_html">楼梯和扶手</a></h1><p>Autodesk.Revit.DB.Architecture命名空间中的Revit API中的类允许访问楼梯和相关构件（如平台和梯段）。可以使用Revit API创建或修改楼梯。Stairs类表示“由构件”创建的楼梯。不能在API中将通过草图创建的楼梯图元作为楼梯对象进行访问。静态方法Stairs.IsByComponent（）可用于确定ElementId是否表示由构件创建的楼梯。</p>
<p> 本节中的页面</p>
<ul>
<li>创建和编辑楼梯</li>
<li>扶手</li>
<li>楼梯注释</li>
<li>楼梯构件</li>
</ul>
<h2 id="创建和编辑楼梯"><a href="#创建和编辑楼梯" class="headerlink" title="创建和编辑楼梯"></a>创建和编辑楼梯</h2><p><strong>StairsEditScope</strong></p>
<p>与Revit文档中其他类型的元素一样，编辑楼梯和楼梯构件需要事务处理。但是，若要创建新构件（如梯段和平台）或创建新楼梯本身，则必须使用Autodesk.Revit.DB.StairsEditScope对象，该对象支持楼梯编辑任务。</p>
<p>StairsEditScope的作用类似于TransactionGroup。启动StairsEditScope后，可以启动事务并编辑楼梯。在StairsEditScope中创建的单个事务不会出现在撤消菜单中。在编辑模式下提交的所有事务将被合并为一个事务，该事务的名称由传递给 StairsEditScope 构造函数的参数指定。</p>
<p>StairsEditScope有两个Start方法。获取现有Stairs对象的ElementId，并为其启动楼梯编辑会话。第二个Start方法采用底部标高和顶部标高的ElementId，并在指定标高中创建具有默认楼梯类型的新空楼梯元素，然后为新楼梯启动楼梯编辑模式。</p>
<p>将梯段和平台添加到楼梯并完成编辑后，请调用 StairsEditScope.Commit() 方法结束楼梯编辑模式。</p>
<p><strong>添加梯段</strong></p>
<ul>
<li>StairsRun类有三个用于为Stairs对象创建新梯段的静态方法：<ul>
<li><strong>CreateSketchedRun</strong> - 通过提供一组边界曲线和踢面曲线来创建草图梯段。</li>
<li><strong>CreateStraightRun</strong> - 创建直线梯段。</li>
<li><strong>CreateSpiralRun</strong> - 通过提供圆心、起始角度和夹角来创建螺旋梯段。</li>
</ul>
</li>
</ul>
<p><strong>添加平台</strong></p>
<p>可以在两个梯段之间添加自动平台或草图平台。静态方法StairsLanding. Canadian AutomaticLanding（）将检查两个楼梯梯段是否满足创建自动平台的限制。静态StairsLanding. random AutomaticLanding（）方法将返回在两个楼梯梯段之间创建的所有平台的Id。</p>
<p>静态StairsLanding. RightSketchedLanding方法通过提供平台的闭合边界曲线，在两个梯段之间创建自定义平台。基本高程的双精度值是CreateSketchedLanding方法的输入参数之一。标高有以下限制：</p>
<ul>
<li>底部高程相对于楼梯的底部高程。</li>
<li>底部高程将自动舍入为踢面高度的倍数。</li>
<li>基础标高应等于或大于踢面高度的一半。</li>
</ul>
<p><strong>例子</strong></p>
<p>下面的示例将创建一个新的Stairs对象、两个梯段（一个为草图梯段，一个为直线梯段）以及它们之间的平台。</p>
<p>代码区域：创建楼梯、楼梯平台和平台</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// FailurePreprocessor class required for StairsEditScope</span></span><br><span class="line"><span class="keyword">class</span> <span class="title">StairsFailurePreprocessor</span> : <span class="title">IFailuresPreprocessor</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> FailureProcessingResult <span class="title">PreprocessFailures</span>(<span class="params">FailuresAccessor failuresAccessor</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Use default failure processing</span></span><br><span class="line">        <span class="keyword">return</span> FailureProcessingResult.Continue; </span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> ElementId <span class="title">CreateStairs</span>(<span class="params">Document document, Level levelBottom, Level levelTop</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ElementId newStairsId = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (StairsEditScope newStairsScope = <span class="keyword">new</span> StairsEditScope(document, <span class="string">&quot;New Stairs&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        newStairsId = newStairsScope.Start(levelBottom.Id, levelTop.Id);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">using</span> (Transaction stairsTrans = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Add Runs and Landings to Stairs&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            stairsTrans.Start();</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Create a sketched run for the stairs</span></span><br><span class="line">            IList bdryCurves = <span class="keyword">new</span> List();</span><br><span class="line">            IList riserCurves = <span class="keyword">new</span> List();</span><br><span class="line">            IList pathCurves = <span class="keyword">new</span> List();</span><br><span class="line">            XYZ pnt1 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pnt2 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pnt3 = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ pnt4 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// boundaries</span></span><br><span class="line">            bdryCurves.Add(Line.CreateBound(pnt1, pnt2));</span><br><span class="line">            bdryCurves.Add(Line.CreateBound(pnt3, pnt4));</span><br><span class="line"></span><br><span class="line">            <span class="comment">// riser curves</span></span><br><span class="line">            <span class="keyword">const</span> <span class="built_in">int</span> riserNum = <span class="number">20</span>;</span><br><span class="line">            <span class="keyword">for</span> (<span class="built_in">int</span> ii = <span class="number">0</span>; ii &lt;= riserNum; ii++)</span><br><span class="line">            &#123;</span><br><span class="line">                XYZ end0 = (pnt1 + pnt2)  ii / (<span class="built_in">double</span>)riserNum;</span><br><span class="line">                XYZ end1 = (pnt3 + pnt4)  ii / (<span class="built_in">double</span>)riserNum;</span><br><span class="line">                XYZ end2 = <span class="keyword">new</span> XYZ(end1.X, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">                riserCurves.Add(Line.CreateBound(end0, end2));</span><br><span class="line">            &#125;</span><br><span class="line"></span><br><span class="line">            <span class="comment">//stairs path curves</span></span><br><span class="line">            XYZ pathEnd0 = (pnt1 + pnt3) / <span class="number">2.0</span>;</span><br><span class="line">            XYZ pathEnd1 = (pnt2 + pnt4) / <span class="number">2.0</span>;</span><br><span class="line">            pathCurves.Add(Line.CreateBound(pathEnd0, pathEnd1));</span><br><span class="line"></span><br><span class="line">            StairsRun newRun1 = StairsRun.CreateSketchedRun(document, newStairsId, levelBottom.Elevation, bdryCurves, riserCurves, pathCurves);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Add a straight run</span></span><br><span class="line">            Line locationLine = Line.CreateBound(<span class="keyword">new</span> XYZ(<span class="number">20</span>, <span class="number">-5</span>, newRun1.TopElevation), <span class="keyword">new</span> XYZ(<span class="number">35</span>, <span class="number">-5</span>, newRun1.TopElevation));</span><br><span class="line">            StairsRun newRun2 = StairsRun.CreateStraightRun(document, newStairsId, locationLine, StairsRunJustification.Center);</span><br><span class="line">            newRun2.ActualRunWidth = <span class="number">10</span>;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Add a landing between the runs</span></span><br><span class="line">            CurveLoop landingLoop = <span class="keyword">new</span> CurveLoop();</span><br><span class="line">            XYZ p1 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">10</span>, <span class="number">0</span>); </span><br><span class="line">            XYZ p2 = <span class="keyword">new</span> XYZ(<span class="number">20</span>, <span class="number">10</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ p3 = <span class="keyword">new</span> XYZ(<span class="number">20</span>, <span class="number">-10</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ p4 = <span class="keyword">new</span> XYZ(<span class="number">15</span>, <span class="number">-10</span>, <span class="number">0</span>);</span><br><span class="line">            Line curve_1 = Line.CreateBound(p1, p2);</span><br><span class="line">            Line curve_2 = Line.CreateBound(p2, p3);</span><br><span class="line">            Line curve_3 = Line.CreateBound(p3, p4);</span><br><span class="line">            Line curve_4 = Line.CreateBound(p4, p1);</span><br><span class="line"></span><br><span class="line">            landingLoop.Append(curve_1);</span><br><span class="line">            landingLoop.Append(curve_2);</span><br><span class="line">            landingLoop.Append(curve_3);</span><br><span class="line">            landingLoop.Append(curve_4);</span><br><span class="line">            StairsLanding newLanding = StairsLanding.CreateSketchedLanding(document, newStairsId, landingLoop, newRun1.TopElevation);</span><br><span class="line"></span><br><span class="line">            stairsTrans.Commit();</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="comment">// A failure preprocessor is to handle possible failures during the edit mode commitment process.</span></span><br><span class="line">        newStairsScope.Commit(<span class="keyword">new</span> StairsFailurePreprocessor());</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> newStairsId;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>从上面的例子产生的楼梯：<img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/stairs.jpg" alt="img"></p>
<p><strong>多层楼梯</strong> </p>
<p>MultistoryStairs类允许楼梯跨越多个标高。多层楼梯元素可以包含多个楼梯，这些楼梯的范围由底部标高和顶部标高控制。 此元素将包含一个或多个Stairs元素。楼梯元素是： 复制到由共享相同标高高度的相同楼梯实例组覆盖的每个标高的参考实例， 或未连接到具有相同标高高度的组的单个Stairs实例。 默认情况下，向多层楼梯添加新标高时，新楼梯将添加到组中。对于不同标高的重复楼梯组，实例可以作为Stairs元素的子元素找到。通过修改关联的Stairs实例，可以一起编辑连接组中的楼梯。对于需要特殊设计的特定楼层，可以使用“取消锁定”方法将楼梯从组中分离出来-对取消锁定的楼梯所做的更改不会影响图元中的其他任何实例。稍后可以使用“锁定”方法将楼梯添加回组中，但是对楼梯所做的任何更改都将丢失，因为楼梯的属性将被组规范覆盖。</p>
<p>代码区域：创建多层楼梯</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// create new MultistoryStairs </span></span><br><span class="line">MultistoryStairs multistoryStairs = MultistoryStairs.Create(stairs);</span><br><span class="line"></span><br><span class="line"><span class="comment">// get all levels that can be connected to this multistoryStairs</span></span><br><span class="line">IEnumerable levelIds = <span class="keyword">new</span> FilteredElementCollector(doc).OfClass(<span class="keyword">typeof</span>(Level)).Cast().Where(q =&gt; multistoryStairs.CanConnectLevel(q.Id))</span><br><span class="line">.Select(q =&gt; q.Id);</span><br><span class="line"></span><br><span class="line"><span class="comment">// Connect the levels to the multistoryStairs</span></span><br><span class="line"><span class="comment">// The input to ConnectLevels is a HashSet or SortedSet, so a HashSet is created from the IEnumerable returned by FilteredElementCollector</span></span><br><span class="line">multistoryStairs.ConnectLevels(<span class="keyword">new</span> HashSet(levelIds));</span><br></pre></td></tr></table></figure>

<p>当使用StairsEditScope.Start（ElementId，ElementId）方法创建新楼梯时，它们具有与其关联的默认扶手。但是，Railing.Create（）方法可用于在不带扶手的楼梯的楼梯元素的所有边上创建具有指定扶手类型的新扶手。与需要使用StairsEditScope创建梯段和平台不同，扶手创建不能在打开的楼梯编辑任务中执行。 由于无法为已具有关联扶手的楼梯创建扶手，因此下面的示例在创建新扶手之前删除与楼梯对象关联的现有扶手。</p>
<p>代码区域：创建扶手</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateRailing</span>(<span class="params">Document document, Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">using</span> (Transaction trans = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Create Railings&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        trans.Start();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Delete existing railings</span></span><br><span class="line">        ICollection railingIds = stairs.GetAssociatedRailings();</span><br><span class="line">        <span class="keyword">foreach</span> (ElementId railingId <span class="keyword">in</span> railingIds)</span><br><span class="line">        &#123;</span><br><span class="line">            document.Delete(railingId);</span><br><span class="line">        &#125;</span><br><span class="line">        <span class="comment">// Find RailingType</span></span><br><span class="line">        FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">        ICollection RailingTypeIds = collector.OfClass(<span class="keyword">typeof</span>(RailingType)).ToElementIds();</span><br><span class="line">        Railing.Create(document, stairs.Id, RailingTypeIds.First(), RailingPlacementPosition.Treads);</span><br><span class="line">        trans.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="扶手"><a href="#扶手" class="headerlink" title="扶手"></a>扶手</h2><p>Autodesk.Revit.DB.Architecture.Railing类表示Autodesk Revit项目中的扶手元素。尽管扶手与楼梯关联，但它们也可以与其他主体（如楼板）关联，也可以放置在空间中。扶手可以是连续的或不连续的。如果它们是不连续的，则仅提供有限的访问级别。</p>
<p>可以使用GetAssociatedRailings（）方法从Stairs类中检索与楼梯关联的扶手。只有少数属性和方法专用于栏杆扶手，例如返回顶部栏杆的ElementId的TopRail属性和指示栏杆扶手是否翻转的Flipped属性。Railing.Flip（）方法翻转扶手，而RemoveHost（）方法将删除扶手与其主体之间的关联。</p>
<p>下面的示例检索与Stairs对象关联的所有栏杆扶手，并翻转系统生成的默认栏杆扶手。</p>
<p>代码区域：使用扶手</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">FlipDefaultRailings</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; railingIds = stairs.GetAssociatedRailings();</span><br><span class="line">    Transaction trans = <span class="keyword">new</span> Transaction(stairs.Document, <span class="string">&quot;Flip Railings&quot;</span>);</span><br><span class="line">    trans.Start();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId railingId <span class="keyword">in</span> railingIds)</span><br><span class="line">    &#123;</span><br><span class="line">        Railing railing = stairs.Document.GetElement(railingId) <span class="keyword">as</span> Railing;</span><br><span class="line">        <span class="keyword">if</span> (railing.IsDefault == <span class="literal">true</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            railing.Flip();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    trans.Commit();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>Railing类具有Create方法，该方法可自动在楼梯元素的所有侧面上创建具有指定扶手类型的新扶手。扶手的创建将在“创建和编辑楼梯”部分中进行演示。</p>
<p>RailingType类表示生成扶手时使用的扶手类型。它包含许多关于扶手的属性，例如主扶手和次扶手以及顶部扶手的高度、横向偏移和类型。</p>
<p> 代码区域：RailingType</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetRailingType</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; railingIds = stairs.GetAssociatedRailings();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId railingId <span class="keyword">in</span> railingIds)</span><br><span class="line">    &#123;</span><br><span class="line">        Railing railing = stairs.Document.GetElement(railingId) <span class="keyword">as</span> Railing;</span><br><span class="line">        RailingType railingType = stairs.Document.GetElement(railing.GetTypeId()) <span class="keyword">as</span> RailingType;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Format railing type info for display</span></span><br><span class="line">        <span class="built_in">string</span> info = <span class="string">&quot;Railing Type:  &quot;</span> + railingType.Name;</span><br><span class="line">        info += <span class="string">&quot;\nPrimary Handrail Height:  &quot;</span> + railingType.PrimaryHandrailHeight;</span><br><span class="line">        info += <span class="string">&quot;\nTop Rail Height:  &quot;</span> + railingType.TopRailHeight;</span><br><span class="line"></span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="楼梯注释"><a href="#楼梯注释" class="headerlink" title="楼梯注释"></a>楼梯注释</h2><p><strong>楼梯注释</strong></p>
<p>StairsPath类可用于注释楼梯的坡度方向和行走线。静态StairsPath.Create（）方法将在楼梯必须可见的特定平面视图中为具有指定楼梯路径类型的指定楼梯创建新楼梯路径。</p>
<p>在Revit UI中编辑楼梯路径时，StairsPath类具有与“属性”窗口中可用的属性相同的属性，例如设置上下方向文字沿着或是否应显示文字的属性。此外，可以指定上下文字的偏移，也可以指定楼梯路径相对于楼梯中心线的偏移。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-98F7477B-3F67-4E52-BDC3-6B63ECA6B700.jpg" alt="img"></p>
<p>下面的示例在项目中查找StairsPathType和FloorPlan，并使用它们为给定的Stairs创建新的StairsPath。</p>
<p>代码区域：创建楼梯路径</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">CreateStairsPath</span>(<span class="params">Document document, Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Transaction transNewPath = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;New Stairs Path&quot;</span>);</span><br><span class="line">    transNewPath.Start();</span><br><span class="line">            </span><br><span class="line">    <span class="comment">// Find StairsPathType</span></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;ElementId&gt; stairsPathIds = collector.OfClass(<span class="keyword">typeof</span>(StairsPathType)).ToElementIdsElementId();</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Find a FloorPlan</span></span><br><span class="line">    ElementId planViewId = ElementId.InvalidElementId;</span><br><span class="line">    FilteredElementCollector viewCollector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;ElementId&gt; viewIds = viewCollector.OfClass(<span class="keyword">typeof</span>(View)).ToElementIdsElementId();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId viewId <span class="keyword">in</span> viewIds)</span><br><span class="line">    &#123;</span><br><span class="line">        View view = document.GetElement(viewId) <span class="keyword">as</span> View;</span><br><span class="line">        <span class="keyword">if</span> (view.ViewType == ViewType.FloorPlan)</span><br><span class="line">        &#123;</span><br><span class="line">            planViewId = view.Id;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">            </span><br><span class="line">    LinkElementId stairsLinkId = <span class="keyword">new</span> LinkElementId(stairs.Id);</span><br><span class="line">    StairsPath.Create(stairs.Document, stairsLinkId, stairsPathIds.First(), planViewId);</span><br><span class="line">    transNewPath.Commit();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>StairsPath具有StairsPathType。楼梯路径类型可从两个预定义的系统族中获得：“自动向上&#x2F;向下方向”和“固定向上方向”。可用于这两种类型的属性作为StairsPathType类中的属性提供，例如FullStepArrow和DistanceToCutMark。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-21CCA05E-3A7C-4CA3-AF96-8BBB88F775E7.jpg" alt="img"></p>
<p>CutMarkType类表示Revit UI中的剪切标记类型，它具有表示在UI中编辑剪切标记类型时可用的相同属性的属性，例如CutLineAngle和CutLineExtension。它与StairsType对象相关联，可以使用BuiltInParameter STAIRSTYPE_CUTMARK_TYPE进行检索，如下所示。</p>
<p>代码区域：获取楼梯的CutMarkType</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> CutMarkType <span class="title">GetCutMark</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    CutMarkType cutMarkType = <span class="literal">null</span>;</span><br><span class="line">    StairsType stairsType = stairs.Document.GetElement(stairs.GetTypeId()) <span class="keyword">as</span> StairsType;</span><br><span class="line">    Parameter paramCutMark = stairsType.get_Parameter(BuiltInParameter.STAIRSTYPE_CUTMARK_TYPE);</span><br><span class="line">    <span class="keyword">if</span> (paramCutMark.StorageType == StorageType.ElementId)  <span class="comment">// should be an element id</span></span><br><span class="line">    &#123;</span><br><span class="line">        ElementId cutMarkId = paramCutMark.AsElementId();</span><br><span class="line">        cutMarkType = stairs.Document.GetElement(cutMarkId) <span class="keyword">as</span> CutMarkType;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> cutMarkType;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="楼梯构件"><a href="#楼梯构件" class="headerlink" title="楼梯构件"></a>楼梯构件</h2><p><strong>楼梯构件</strong></p>
<p>Stairs类表示Revit中的楼梯图元，并包含表示有关踏步、高度、楼层数以及楼梯高度、底部标高和顶部标高的信息的属性。Stairs类的方法可用于获取楼梯平台构件、楼梯梯段构件和楼梯支撑。</p>
<p>下面的示例按构件查找所有楼梯，并将有关每个楼梯的一些信息输出到TaskDialog对话框。请注意，此示例使用带有BuiltInCategory.OST_Stairs的类别过滤器，该过滤器将返回所有楼梯的ElementId，因此在从文档中检索时将每个ElementId转换为Stairs类之前，需要进行测试以查看每个ElementId是否代表Stairs By Component。</p>
<p>代码区域：获取楼梯信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Stairs <span class="title">GetStairInfo</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Stairs stairs = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;ElementId&gt; stairsIds = collector.WhereElementIsNotElementType().OfCategory(BuiltInCategory.OST_Stairs).ToElementIdsElementId();</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId stairId <span class="keyword">in</span> stairsIds)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (Stairs.IsByComponent(document, stairId) == <span class="literal">true</span>)</span><br><span class="line">        &#123;</span><br><span class="line">            stairs = document.GetElement(stairId) <span class="keyword">as</span> Stairs;</span><br><span class="line">                   </span><br><span class="line">            <span class="comment">// Format the information</span></span><br><span class="line">            String info = <span class="string">&quot;\nNumber of stories:  &quot;</span> + stairs.NumberOfStories;</span><br><span class="line">            info += <span class="string">&quot;\nHeight of stairs:  &quot;</span> + stairs.Height;</span><br><span class="line">            info += <span class="string">&quot;\nNumber of treads:  &quot;</span> + stairs.ActualTreadsNumber;</span><br><span class="line">            info += <span class="string">&quot;\nTread depth:  &quot;</span> + stairs.ActualTreadDepth;</span><br><span class="line">            </span><br><span class="line">            <span class="comment">// Show the information to the user.</span></span><br><span class="line">            TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">  </span><br><span class="line">    <span class="keyword">return</span> stairs;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>StairsType类表示Stairs元素的类型。它包含有关楼梯的信息，例如楼梯对象中所有梯段和平台的类型、楼梯左侧、右侧和中间支撑的类型和偏移，以及与楼梯生成相关的许多其他特性，例如楼梯图元上每个踢面的最大高度。下面的示例获取Stairs元素的StairsType，并在TaskDialog中显示有关该元素的一些信息。</p>
<p>代码区域：获取楼梯类型信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetStairsType</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    StairsType stairsType = stairs.Document.GetElement(stairs.GetTypeId()) <span class="keyword">as</span> StairsType;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Format stairs type info for display</span></span><br><span class="line">    <span class="built_in">string</span> info = <span class="string">&quot;Stairs Type:  &quot;</span> + stairsType.Name;</span><br><span class="line">    info += <span class="string">&quot;\nLeft Lateral Offset:  &quot;</span> + stairsType.LeftLateralOffset;</span><br><span class="line">    info += <span class="string">&quot;\nRight Lateral Offset:  &quot;</span> + stairsType.RightLateralOffset;</span><br><span class="line">    info += <span class="string">&quot;\nMax Riser Height:  &quot;</span> + stairsType.MaxRiserHeight;</span><br><span class="line">    info += <span class="string">&quot;\nMin Run Width:  &quot;</span> + stairsType.MinRunWidth;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>梯段</strong></p>
<p>楼梯构件由梯段、平台和支撑组成。这些项中的每一项都可以从Stairs类中检索。梯段在Revit API中由StairsRun类表示。下面的示例获取Stairs对象的每个梯段，并确保它以踢面开始和结束。</p>
<p>代码区域：使用StairsRun</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">AddStartandEndRisers</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; runIds = stairs.GetStairsRuns();</span><br><span class="line">            </span><br><span class="line">    <span class="keyword">foreach</span> (ElementId runId <span class="keyword">in</span> runIds)</span><br><span class="line">    &#123;</span><br><span class="line">        StairsRun run = stairs.Document.GetElement(runId) <span class="keyword">as</span> StairsRun;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != run)</span><br><span class="line">        &#123;</span><br><span class="line">            run.BeginsWithRiser = <span class="literal">true</span>;</span><br><span class="line">            run.EndsWithRiser = <span class="literal">true</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>StairsRun类提供对梯段属性的访问，例如StairsRunStyle（直线、斜梯等），BaseElevation、TopElevation和有关高程的属性。StairsRun类中还有一些方法可用于访问梯段承载的支撑，可以是全部支撑，也可以仅是梯段边界左侧或右侧的支撑。GetStairsPath（）方法将返回表示梯段上楼梯路径的曲线，这些曲线将投影到楼梯的底部标高上。GetFootprintBoundary（）方法返回梯段的边界曲线，这些曲线也投影到楼梯的底部标高上。</p>
<p>StairsRun类有三个用于创建新梯段的静态方法。这些将在“创建和编辑楼梯”部分中介绍。</p>
<p>StairsRunType类表示StairsRun的类型。它包含有关梯段踏板和宽度的许多特性以及有关梯段的其他信息。下面的示例获取Stairs元素中第一个梯段的StairsRunType，并显示踢面和踏步厚度沿着以及类型名称。</p>
<p>代码区域：获取StairsRunType信息</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetRunType</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; runIds = stairs.GetStairsRuns();</span><br><span class="line"></span><br><span class="line">    ElementId firstRunId = runIds.First();</span><br><span class="line"></span><br><span class="line">    StairsRun firstRun = stairs.Document.GetElement(firstRunId) <span class="keyword">as</span> StairsRun;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != firstRun)</span><br><span class="line">    &#123;</span><br><span class="line">        StairsRunType runType = stairs.Document.GetElement(firstRun.GetTypeId()) <span class="keyword">as</span> StairsRunType;</span><br><span class="line">        <span class="comment">// Format landing type info for display</span></span><br><span class="line">        <span class="built_in">string</span> info = <span class="string">&quot;Stairs Run Type:  &quot;</span> + runType.Name;</span><br><span class="line">        info += <span class="string">&quot;\nRiser Thickness:  &quot;</span> + runType.RiserThickness;</span><br><span class="line">        info += <span class="string">&quot;\nTread Thickness:  &quot;</span> + runType.TreadThickness;</span><br><span class="line"></span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>平台</strong></p>
<p>平台由StairsLanding类表示。下面的示例查找Stairs对象的每个平台的厚度。</p>
<p>代码区域：使用楼梯平台</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetStairLandings</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; landingIds = stairs.GetStairsLandings();</span><br><span class="line">    <span class="built_in">string</span> info = <span class="string">&quot;Number of landings:  &quot;</span> + landingIds.Count;</span><br><span class="line"></span><br><span class="line">    <span class="built_in">int</span> landingIndex = <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId landingId <span class="keyword">in</span> landingIds)</span><br><span class="line">    &#123;</span><br><span class="line">        landingIndex++;</span><br><span class="line">        StairsLanding landing = stairs.Document.GetElement(landingId) <span class="keyword">as</span> StairsLanding;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != landing)</span><br><span class="line">        &#123;</span><br><span class="line">            info += <span class="string">&quot;\nThickness of Landing &quot;</span> + landingIndex + <span class="string">&quot;:  &quot;</span> + landing.Thickness;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>与StairsRun类似，StairsLanding具有GetStairsPath（）方法和GetFootprintBoundary（）方法，前者返回表示平台上投影到楼梯基层的楼梯路径的曲线，后者返回平台的边界曲线，也投影到楼梯基层。同样类似于StairsRun，有一种方法可以获取平台承载的所有支撑。</p>
<p>StairsLanding类有一个在两个梯段之间创建新平台的方法。它将在“创建和编辑楼梯”部分中介绍。</p>
<p>StairsLandingType类表示Revit API中的平台类型。StairsLandingType类只有两个特定于它的属性，即IsMonolithic（如果楼梯平台是整体的，则为真）和Thickness（表示楼梯平台的厚度）。</p>
<p><strong>楼梯连接</strong><br>Both StairsRun and StairsLanding have a GetConnections() method which provides information about connections among stairs components (run to run, or run to landing). The method returns a collection of StairsComponentConnection objects which have properties about each connection, including the connection type (to a landing, the start of a stairs run, or the end of a stairs run) and the Id of the connected stairs component.<br>StairsRun和StairsLanding都具有GetConnections（）方法，该方法提供有关楼梯构件之间连接的信息（梯段到梯段，或梯段到平台）。该方法返回一个StairsStringentConnection对象的集合，这些对象具有关于每个连接的属性，包括连接类型（连接平台、楼梯梯段起点或楼梯梯段终点）和连接的楼梯构件的ID。</p>
<p><strong>支撑</strong></p>
<p>Revit API不显示楼梯支撑类。获取楼梯、楼梯梯段或楼梯平台的支撑时，支撑将为常规Revit图元。下面的示例获取Stairs对象的所有支撑的名称。</p>
<p>代码区域：获取楼梯支撑</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">GetStairSupports</span>(<span class="params">Stairs stairs</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    ICollection&lt;ElementId&gt; supportIds = stairs.GetStairsSupports();</span><br><span class="line">    <span class="built_in">string</span> info = <span class="string">&quot;Number of supports:  &quot;</span> + supportIds.Count;</span><br><span class="line"></span><br><span class="line">    <span class="built_in">int</span> supportIndex = <span class="number">0</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (ElementId supportId <span class="keyword">in</span> supportIds)</span><br><span class="line">    &#123;</span><br><span class="line">        supportIndex++;</span><br><span class="line">        Element support = stairs.Document.GetElement(supportId);</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != support)</span><br><span class="line">        &#123;</span><br><span class="line">            info += <span class="string">&quot;\nName of support &quot;</span> + supportIndex + <span class="string">&quot;:  &quot;</span> + support.Name;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2>
    </div>
    
    
    
    
    
    
    
</div>

            <footer id="footer">
    <div id="footer-wrap">
        <div>
            &copy;
            2022 - 2024 Hexo
            <span id="footer-icon">
                <i class="fa-solid fa-font-awesome fa-fw"></i>
            </span>
            &commat;John Doe
        </div>
        <div>
            Based on the <a target="_blank" rel="noopener" href="https://hexo.io">Hexo Engine</a> &amp;
            <a target="_blank" rel="noopener" href="https://github.com/theme-particlex/hexo-theme-particlex">ParticleX Theme</a>
        </div>
        
    </div>
</footer>

        </div>
        
        <transition name="fade">
            <div id="preview" ref="preview" v-show="previewShow">
                <img id="preview-content" ref="previewContent" />
            </div>
        </transition>
        
    </div>
    <script src="/js/main.js"></script>
    
    




    
</body>
</html>
