
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <title> | funtim</title>
    <meta name="author" content="John Doe" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <link rel="icon" href="/images/avatar.jpg" />
    <link rel="preconnect" href="https://s4.zstatic.net" />
<script src="https://s4.zstatic.net/ajax/libs/vue/3.3.7/vue.global.prod.min.js"></script>
<link rel="stylesheet" href="https://s4.zstatic.net/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
<link rel="preconnect" href="https://fonts.googleapis.cn" />
<link rel="preconnect" href="https://fonts.gstatic.cn" crossorigin />
<link
    rel="stylesheet"
    href="https://fonts.googleapis.cn/css2?family=Fira+Code:wght@400;500;600;700&family=Lexend:wght@400;500;600;700;800;900&family=Noto+Sans+SC:wght@400;500;600;700;800;900&display=swap"
/>
<script> const mixins = {}; </script>

<script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=default"></script>


<script src="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://s4.zstatic.net/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
<link
    rel="stylesheet"
    href="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/styles/github.min.css"
/>
<script src="/js/lib/highlight.js"></script>



<script src="/js/lib/preview.js"></script>









<link rel="stylesheet" href="/css/main.css" />

<meta name="generator" content="Hexo 7.3.0"></head>
<body>
    <div id="layout">
        <transition name="fade">
            <div id="loading" v-show="loading">
                <div id="loading-circle">
                    <h2>LOADING</h2>
                    <p>加载过慢请开启缓存 浏览器默认开启</p>
                    <img src="/images/loading.gif" />
                </div>
            </div>
        </transition>
        <div id="menu" :class="{ hidden: hiddenMenu, 'menu-color': menuColor}">
    <nav id="desktop-menu">
        <a class="title" href="/">
            <span>FUNTIM</span>
        </a>
        
        <a href="/">
            <i class="fa-solid fa-house fa-fw"></i>
            <span>&ensp;Home</span>
        </a>
        
        <a href="/about">
            <i class="fa-solid fa-id-card fa-fw"></i>
            <span>&ensp;About</span>
        </a>
        
        <a href="/archives">
            <i class="fa-solid fa-box-archive fa-fw"></i>
            <span>&ensp;Archives</span>
        </a>
        
        <a href="/categories">
            <i class="fa-solid fa-bookmark fa-fw"></i>
            <span>&ensp;Categories</span>
        </a>
        
        <a href="/tags">
            <i class="fa-solid fa-tags fa-fw"></i>
            <span>&ensp;Tags</span>
        </a>
        
    </nav>
    <nav id="mobile-menu">
        <div class="title" @click="showMenuItems = !showMenuItems">
            <i class="fa-solid fa-bars fa-fw"></i>
            <span>&emsp;FUNTIM</span>
        </div>
        <transition name="slide">
            <div class="items" v-show="showMenuItems">
                
                <a href="/">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-house fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Home</div>
                    </div>
                </a>
                
                <a href="/about">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-id-card fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">About</div>
                    </div>
                </a>
                
                <a href="/archives">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-box-archive fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Archives</div>
                    </div>
                </a>
                
                <a href="/categories">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-bookmark fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Categories</div>
                    </div>
                </a>
                
                <a href="/tags">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-tags fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Tags</div>
                    </div>
                </a>
                
            </div>
        </transition>
    </nav>
</div>
<transition name="fade">
    <div id="menu-curtain" @click="showMenuItems = !showMenuItems" v-show="showMenuItems"></div>
</transition>

        <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
            <div class="article">
    <div>
        <h1></h1>
    </div>
    <div class="info">
        <span class="date">
            <span class="icon">
                <i class="fa-solid fa-calendar fa-fw"></i>
            </span>
            2024/12/28
        </span>
        
        
    </div>
    
    <div class="content" v-pre>
        <h1 id="编辑元素"><a href="#编辑元素" class="headerlink" title="编辑元素"></a><a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_Basic_Interaction_with_Revit_Elements_Editing_Elements_html">编辑元素</a></h1><p>在Revit中，可以使用Revit Platform API移动、复制、旋转、对齐、删除、镜像、编组和排列一个元素或一组元素。在API中使用编辑功能与在Revit UI中使用命令类似。</p>
<p>Pages in this section 本节中的页面</p>
<ul>
<li>Moving Elements 移动元素</li>
<li>Copying Elements 复制元素</li>
<li>Rotating elements 旋转元素</li>
<li>Aligning Elements 对齐元素</li>
<li>Mirroring Elements 镜像元素</li>
<li>Grouping Elements 对元素进行分组</li>
<li>Creating Arrays of Elements 创建元素数组</li>
<li>Deleting Elements 删除元素</li>
<li>Pinned Elements 固定元素</li>
</ul>
<h2 id="移动元素"><a href="#移动元素" class="headerlink" title="移动元素"></a>移动元素</h2><p>ElementTransformUtils类提供两个静态方法来将一个或多个元素从一个位置移动到另一个位置。</p>
<p>表19：移动方法</p>
<table>
<thead>
<tr>
<th><strong>Member</strong></th>
<th>**Description **</th>
</tr>
</thead>
<tbody><tr>
<td>MoveElement( Document, ElementId, XYZ)</td>
<td>将文档中的元素移动指定的向量。</td>
</tr>
<tr>
<td>MoveElements(Document, ICollection, XYZ)</td>
<td>将文档中的几个元素移动指定向量的一组ID。</td>
</tr>
</tbody></table>
<p>注意：当您使用MoveElement（）或MoveElements（）方法时，以下规则适用。这些方法不能将基于标高的图元从标高上移或下移。如果图元基于标高，则不能修改Z坐标值。但是，可以将图元放置在同一标高中的任何位置。同样，某些基于标高的图元具有偏移实例参数，可以使用该参数在Z方向上移动它们。例如，如果在标高1中的原始位置（0，0，0）创建新柱，然后将其移动到新位置（10，20，30），则柱将放置在位置（10，20，0）而不是（10，20，30）。</p>
<p>代码区域10-1：使用MoveElement（）</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MoveColumn</span>(<span class="params">Autodesk.Revit.DB.Document document, FamilyInstance column</span>)</span></span><br><span class="line">    &#123;</span><br><span class="line">            <span class="comment">// get the column current location</span></span><br><span class="line">            LocationPoint columnLocation = column.Location <span class="keyword">as</span> LocationPoint;</span><br><span class="line"></span><br><span class="line">            XYZ oldPlace = columnLocation.Point;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Move the column to new location.</span></span><br><span class="line">            XYZ newPlace = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">20</span>, <span class="number">30</span>);</span><br><span class="line">            ElementTransformUtils.MoveElement(document, column.Id, newPlace);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// now get the column&#x27;s new location</span></span><br><span class="line">            columnLocation = column.Location <span class="keyword">as</span> LocationPoint;</span><br><span class="line">            XYZ newActual = columnLocation.Point;</span><br><span class="line"></span><br><span class="line">            <span class="built_in">string</span> info = <span class="string">&quot;Original Z location: &quot;</span> + oldPlace.Z + </span><br><span class="line">                            <span class="string">&quot;\nNew Z location: &quot;</span> + newActual.Z;</span><br><span class="line"></span><br><span class="line">            TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,info);</span><br><span class="line">    &#125;</span><br></pre></td></tr></table></figure>

<p>移动一个或多个图元时，关联图元也会移动。例如，如果移动带窗的墙，则窗也会移动。 * 无法移动固定的图元。 在Revit中移动图元的另一种方法是使用位置及其衍生对象。在Revit Platform API中，Location对象提供了平移和旋转图元的功能。更多的位置信息和控制可以使用Location对象的派生，如LocationPoint或LocationCurve。如果Location元素向下转换为LocationCurve对象或LocationPoint对象，则直接将曲线或点移动到新位置。</p>
<p>代码区域10-2：使用位置移动</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="built_in">bool</span> <span class="title">MoveUsingLocationCurve</span>(<span class="params">Autodesk.Revit.ApplicationServices.Application application, Wall wall</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        LocationCurve wallLine = wall.Location <span class="keyword">as</span> LocationCurve;</span><br><span class="line">        XYZ translationVec = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">20</span>, <span class="number">0</span>);</span><br><span class="line">        <span class="keyword">return</span> (wallLine.Move(translationVec));</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-CA323378-0ABA-4B2B-B242-2D98C01F0A78-low.png"></p>
<p>图30：使用LocationCurve移动墙</p>
<p>此外，还可以使用LocationCurve Curve属性或LocationPoint Point属性在Revit中移动一个图元。 使用Curve特性将曲线驱动元素移动到任何指定位置。许多图元是曲线驱动的，例如墙、梁和支撑。还可以使用属性调整元素长度的大小。</p>
<p>代码区域10-3：使用曲线移动</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">MoveUsingCurveParam</span>(<span class="params">Autodesk.Revit.ApplicationServices.Application application, Wall wall</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    LocationCurve wallLine = wall.Location <span class="keyword">as</span> LocationCurve;</span><br><span class="line">    XYZ p1 = XYZ.Zero;</span><br><span class="line">    XYZ p2 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">20</span>, <span class="number">0</span>);</span><br><span class="line">    Line newWallLine = Line.CreateBound(p1, p2);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Change the wall line to a new line.</span></span><br><span class="line">    wallLine.Curve = newWallLine;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>还可以使用LocationCurve.JoinType属性获取或设置基于曲线的元素的联接属性。 使用LocationPoint Point属性设置元素的物理位置。</p>
<p>代码区域10-4：使用点移动</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">LocationMove</span>(<span class="params">FamilyInstance column</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        LocationPoint columnPoint = column.Location <span class="keyword">as</span> LocationPoint;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != columnPoint)</span><br><span class="line">        &#123;</span><br><span class="line">                XYZ newLocation = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">20</span>, <span class="number">0</span>);</span><br><span class="line">                <span class="comment">// Move the column to the new location</span></span><br><span class="line">                columnPoint.Point = newLocation;</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="复制元素"><a href="#复制元素" class="headerlink" title="复制元素"></a>复制元素</h2><p>ElementTransformUtils类提供了几个静态方法，用于将一个或多个元素从一个位置复制到另一个位置，可以在同一文档或视图中复制，也可以复制到不同的文档或视图中。</p>
<p>表：复制方法</p>
<table>
<thead>
<tr>
<th><strong>Member</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody><tr>
<td>CopyElement( Document, ElementId, XYZ)</td>
<td>复制元素并将副本放置在给定变换所指示的位置。</td>
</tr>
<tr>
<td>CopyElements(Document, ICollection, XYZ)</td>
<td>复制一组元素，并将副本放置在给定事务指示的位置。</td>
</tr>
<tr>
<td>CopyElements(Document, ICollection, Document, Transform, CopyPasteOptions)</td>
<td>将一组元素从源文档复制到目标文档。</td>
</tr>
<tr>
<td>CopyElements(View, ICollection, View, Transform, CopyPasteOptions)</td>
<td>将一组元素从源视图复制到目标视图。</td>
</tr>
</tbody></table>
<p>所有方法都返回新创建元素的ElementId集合，包括CopyElement（）。该集合包括由于依赖关系而创建的任何元素。</p>
<p>从一个文档复制到另一个文档的方法只能用于复制非视图特定的元素。副本被放置在其各自的原始位置或由可选转换指定的位置。</p>
<p>应使用从一个视图复制到另一个视图的方法来复制视图特定的图元。该方法可用于视图专有图元和模型图元，但绘图视图不能用作模型图元的目标。粘贴的图元将被重新定位，以确保在目标视图中正确放置。例如，从一个标高复制到另一个标高时，标高会发生更改。通过提供可选的Transform参数，可以在目标视图中执行其他转换。此附加变换必须在目标视图的平面内。</p>
<p>从一个视图复制到另一个视图时，源视图和目标视图都必须是能够绘制详图和视图专有图元（如楼板和天花板平面、立面、剖面或绘图视图）的二维图形视图。ElementTransformUtils.GetTransformFromViewToView（）方法将返回从源视图复制到目标视图时应用于元素的转换。</p>
<p>在视图之间或文档之间复制时，可以设置可选的CopyPasteOptions参数以覆盖默认的复制&#x2F;粘贴设置。默认情况下，如果在粘贴操作过程中出现重复的类型名称，Revit将显示一个模式对话框，其中包含仅复制具有唯一名称的类型或取消操作的选项。CopyPasteOptions可用于指定一个自定义处理程序，使用IDuplicateTypeException接口来处理重复的类型名称。</p>
<p>See the Duplicate Views sample in the Revit SDK for a detailed example of copying between documents and between views.<br>有关在文档之间和视图之间复制的详细示例，请参见Revit SDK中的“复制视图”示例。</p>
<h2 id="旋转元素"><a href="#旋转元素" class="headerlink" title="旋转元素"></a>旋转元素</h2><p>ElementTransformUtils类提供了两个静态方法来旋转项目中的一个或多个元素。</p>
<p>表20：旋转方法</p>
<table>
<thead>
<tr>
<th><strong>Member</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody><tr>
<td>RotateElement(Document, ElementId, Line, double)</td>
<td>将文档中的元素围绕给定轴旋转指定的弧度数。</td>
</tr>
<tr>
<td>RotateElements(Document, ICollection, Line, double)</td>
<td>按项目中的ID将多个图元围绕给定轴旋转指定的弧度数。</td>
</tr>
</tbody></table>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-2CDF32C7-BA19-499B-81BE-02A982E310D7-low.png"></p>
<p>图31：逆时针旋转 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/ENU/Revit-API/images/GUID-11A64EB3-0D9F-4A33-8DB7-CBA34CFBD04C-low.png"></p>
<p>图32：顺时针旋转 请注意，锁定的图元不能旋转。</p>
<p>代码区域10-5：使用RotateElement（）</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">RotateColumn</span>(<span class="params">Autodesk.Revit.DB.Document document, Autodesk.Revit.DB.Element element</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    XYZ point1 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">20</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ point2 = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">20</span>, <span class="number">30</span>);</span><br><span class="line">    <span class="comment">// The axis should be a bound line.</span></span><br><span class="line">    Line axis = Line.CreateBound(point1, point2);</span><br><span class="line">    ElementTransformUtils.RotateElement(document, element.Id, axis, Math.PI / <span class="number">3.0</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>如果元素Location可以向下转换为LocationCurve或LocationPoint，则可以直接旋转曲线或点。</p>
<p>代码区域10-6：基于位置曲线旋转</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="built_in">bool</span> <span class="title">LocationRotate</span>(<span class="params">Autodesk.Revit.ApplicationServices.Application application, Autodesk.Revit.DB.Element element</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">bool</span> rotated = <span class="literal">false</span>;</span><br><span class="line">    <span class="comment">// Rotate the element via its location curve.</span></span><br><span class="line">    LocationCurve curve = element.Location <span class="keyword">as</span> LocationCurve;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != curve)</span><br><span class="line">    &#123;</span><br><span class="line">        Curve line = curve.Curve;</span><br><span class="line">        XYZ aa = line.GetEndPoint(<span class="number">0</span>);</span><br><span class="line">        XYZ cc = <span class="keyword">new</span> XYZ(aa.X, aa.Y, aa.Z + <span class="number">10</span>);</span><br><span class="line">        Line axis = Line.CreateBound(aa, cc);</span><br><span class="line">        rotated = curve.Rotate(axis, Math.PI / <span class="number">2.0</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> rotated;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>代码区域10-7：基于位置点旋转</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="built_in">bool</span> <span class="title">LocationRotate</span>(<span class="params">Autodesk.Revit.ApplicationServices.Application application, Autodesk.Revit.Element element</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="built_in">bool</span> rotated = <span class="literal">false</span>;</span><br><span class="line">        LocationPoint location = element.Location <span class="keyword">as</span> LocationPoint;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != location)</span><br><span class="line">        &#123;</span><br><span class="line">                XYZ aa = location.Point;</span><br><span class="line">                XYZ cc = <span class="keyword">new</span> XYZ(aa.X, aa.Y, aa.Z + <span class="number">10</span>);</span><br><span class="line">                Line axis = Line.CreateBound(aa, cc);                </span><br><span class="line">            rotated = location.Rotate(axis, Math.PI / <span class="number">2.0</span>);</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> rotated;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="对齐元素"><a href="#对齐元素" class="headerlink" title="对齐元素"></a>对齐元素</h2><p>ItemFactoryBase.NewAlignment（）方法可以在两个引用之间创建新的锁定对齐。这两个引用必须是以下组合之一：</p>
<ul>
<li>2个平面</li>
<li>2条线</li>
<li>线和点</li>
<li>直线和参考平面</li>
<li>2个弧</li>
<li>2个圆柱面</li>
</ul>
<p>这些参照必须已经几何对齐，因为此函数不会强制它们对齐。如果可以创建对齐，则返回一个表示锁定对齐的新Dimension对象。否则将抛出异常。</p>
<p>NewAlignment（）方法还需要一个视图来确定路线的方向。</p>
<p>请参见SDK Samples中包含的FamilyCreation文件夹中的“桁架”示例。其中有几个使用NewAlignment（）的示例，例如将新桁架的下弦杆锁定到底部参照平面。</p>
<h2 id="镜像元素"><a href="#镜像元素" class="headerlink" title="镜像元素"></a>镜像元素</h2><p>ElementTransformUtils类提供两个静态方法来镜像项目中的一个或多个元素。</p>
<p>表21：镜像方法</p>
<table>
<thead>
<tr>
<th><strong>Member 构件</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody><tr>
<td>MirrorElement(Document, ElementId, Plane)</td>
<td>关于几何平面镜像一个元素。</td>
</tr>
<tr>
<td>MirrorElements(Document, ICollection, Plane, Boolean)</td>
<td>关于几何平面镜像多个元素。可以在原始几何体或副本上执行。</td>
</tr>
</tbody></table>
<p>执行镜像操作后，可以从“选择元素集”（Selection ElementSet）访问新元素。</p>
<p>ElementTransformUtils. Canadian Element（）和ElementTransformUtils. Canadian Elements（）可用于在尝试镜像元素之前确定是否可以镜像一个或多个元素。</p>
<p>下面的代码演示如何使用根据墙的侧面计算的平面镜像墙。</p>
<p>代码区域10-8：镜像墙壁</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">MirrorWall</span>(<span class="params">Autodesk.Revit.DB.Document document, Wall wall</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Reference reference = HostObjectUtils.GetSideFaces(wall, ShellLayerType.Exterior).First();</span><br><span class="line"></span><br><span class="line">        <span class="comment">// get one of the wall&#x27;s major side faces</span></span><br><span class="line">        Face face = wall.GetGeometryObjectFromReference(reference) <span class="keyword">as</span> Face; </span><br><span class="line"></span><br><span class="line">        UV bboxMin = face.GetBoundingBox().Min;</span><br><span class="line">        <span class="comment">// create a plane based on this side face with an offset of 10 in the X &amp; Y directions</span></span><br><span class="line"></span><br><span class="line">        Plane plane = <span class="keyword">new</span> Plane(face.ComputeNormal(bboxMin), </span><br><span class="line">                face.Evaluate(bboxMin).Add(<span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">10</span>, <span class="number">0</span>)));</span><br><span class="line"></span><br><span class="line">        ElementTransformUtils.MirrorElement(document, wall.Id, plane);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>每个FamilyInstance都有一个镜像属性。它指示是否镜像FamilyInstance（例如柱）。</p>
<h2 id="对元素进行分组"><a href="#对元素进行分组" class="headerlink" title="对元素进行分组"></a>对元素进行分组</h2><p>Revit 平台 API 使用 Creation.Document.NewGroup（） 方法选择一个图元或多个图元或组，然后将它们组合在一起。对于您放置的组的每个实例，它们之间都有关联。例如，您可以创建一个包含床、墙和窗户的组，然后在项目中放置该组的多个实例。如果修改一个组中的墙，则该墙会针对该组的所有实例进行更改。这使得修改建筑模型变得更加容易，因为您可以在一次操作中更改组的多个实例。</p>
<p>代码区域 10-9：创建组</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">Group <span class="keyword">group</span> = <span class="literal">null</span>;</span><br><span class="line">UIDocument uidoc = <span class="keyword">new</span> UIDocument(document);</span><br><span class="line">ICollection selectedIds = uidoc.Selection.GetElementIds();</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> (selectedIds.Count &gt; <span class="number">0</span>)</span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Group all selected elements</span></span><br><span class="line">    <span class="keyword">group</span> = document.Create.NewGroup(selectedIds);</span><br><span class="line"></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>最初，该组具有通用名称，例如 Group 1。可以通过更改组类型的名称来修改它，如下所示：</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Change the default group name to a new name &quot;MyGroup&quot;</span></span><br><span class="line"><span class="keyword">group</span>.GroupType.Name = <span class="string">&quot;MyGroup&quot;</span>;</span><br></pre></td></tr></table></figure>

<p>Revit 中有三种类型的组;模型组、详图组和附加详图组。所有 API 都是使用 NewGroup（） 方法创建的。创建的 Group 的类型取决于传递的 Elements。</p>
<ul>
<li>如果未传递详图元素，则会创建一个模型组。</li>
<li>如果所有元素都是详图元素，则会创建一个详图组。</li>
<li>如果同时包含两种类型的元素，则会创建并返回包含 Attached Detail Group 的模型组。</li>
</ul>
<p><em><strong>注意</strong></em>对元素进行分组后，可以从项目中删除这些元素。</p>
<ul>
<li>删除模型组中的模型元素后，当鼠标光标悬停在组上或单击该组时，该模型元素仍然可见，即使应用程序向 UI 返回 Succeeded 也是如此。实际上，模型元素已被删除，您无法选择或访问该元素。</li>
<li>当组实例的最后一个成员被删除、排除或从项目中移除时，模型组实例将被删除。</li>
</ul>
<p>对元素进行分组时，无法移动或旋转它们。如果对分组的元素执行这些操作，则元素不会发生任何变化，但 Move（） 或 Rotate（） 方法返回 true。</p>
<p>如果不对维度和标记引用的元素进行分组，则无法对它们进行分组。如果这样做，API 调用将失败。</p>
<p>您可以对引用模型组中的模型元素的维度和标签进行分组。尺寸和标记将添加到附加的详图组中。如果不对父组执行相同的操作，则无法移动、复制、旋转、阵列或镜像附着的详图组。</p>
<h2 id="创建元素阵列"><a href="#创建元素阵列" class="headerlink" title="创建元素阵列"></a>创建元素阵列</h2><p>Revit 平台 API 提供了两个类，即 LinearArray 和 RadialArray，用于对项目中的一个或多个图元进行阵列。这些类提供静态方法，用于创建一个或多个选定组件的线性或径向阵列。线性阵列表示从一个点沿直线创建的阵列，而径向阵列表示沿圆弧创建的阵列。</p>
<p>作为使用阵列的示例，您可以选择位于同一墙中的门和窗，然后创建门、墙和窗配置的多个实例。</p>
<p>LinearArray 和 RadialArray 都提供了对一个或多个元素进行阵列的方法，而无需进行分组和关联。尽管类似于用于阵列元素的 Create（） 方法，但每个生成的元素都独立于其他元素，并且可以在不影响其他元素的情况下进行操作。有关可用于创建线性或径向阵列的方法的更多信息，请参阅下表。</p>
<p>表 22：LinearArray 方法</p>
<table>
<thead>
<tr>
<th><strong>Member 成员</strong></th>
<th><strong>Description 描述</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Create(Document, View, ElementId, int, XYZ, ArrayAnchorMember)</td>
<td>按指定数字对项目中的一个元素进行阵列。</td>
</tr>
<tr>
<td>Create(Document, View, ICollection, int, XYZ, ArrayAnchorMember)</td>
<td>按指定数字对项目中的一组元素进行阵列。</td>
</tr>
<tr>
<td>ArrayElementWithoutAssociation(Document, View, ElementId, int, XYZ, ArrayAnchorMember)</td>
<td>按指定数字对项目中的一个元素进行阵列。生成的元素不与线性阵列关联。</td>
</tr>
<tr>
<td>ArrayElementsWithoutAssociation(Document, View, ICollection, int, XYZ, ArrayAnchorMember)</td>
<td>按指定数字对项目中的一组元素进行阵列排列。生成的元素不与线性阵列关联。</td>
</tr>
</tbody></table>
<p>表 23：RadialArray 方法</p>
<table>
<thead>
<tr>
<th><strong>Member 成员</strong></th>
<th><strong>Description 描述</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Create(Document, View, ElementId, int, Line, double, ArrayAnchorMember)</td>
<td>根据输入旋转轴对项目中的一个元素进行阵列。</td>
</tr>
<tr>
<td>Create(Document, View, ICollection, int, Line, double, ArrayAnchorMember)</td>
<td>根据输入旋转轴对项目中的一组元素进行阵列。</td>
</tr>
<tr>
<td>ArrayElementWithoutAssociation(Document, View, ElementId, int, Line, double, ArrayAnchorMember)</td>
<td>根据输入旋转轴对项目中的一个元素进行阵列.生成的元素不与线性阵列关联。</td>
</tr>
<tr>
<td>ArrayElementsWithoutAssociation(Document, View, ICollection, int, Line, double, ArrayAnchorMember)</td>
<td>根据输入旋转轴对项目中的一组元素进行阵列。生成的元素不与线性阵列关联。</td>
</tr>
</tbody></table>
<p>如果您需要创建组件的多个实例并同时操作它们，则排列元素的方法非常有用。数组中的每个实例都可以是组的成员。</p>
<p>注意：使用方法对元素进行阵列时，以下规则适用：</p>
<ul>
<li>执行 Linear 和 Radial Array 操作时，依赖于阵列元素的元素也会排列。</li>
<li>某些元素无法排列，因为它们无法分组。有关组和阵列限制的详细信息，请参见《Revit 用户指南》。</li>
<li>大多数注释符号不支持数组。</li>
</ul>
<h2 id="删除元素"><a href="#删除元素" class="headerlink" title="删除元素"></a>删除元素</h2><p>Revit 平台 API 提供了 Delete（） 方法，用于删除项目中的一个或多个图元。</p>
<p> 表 23：删除成员</p>
<table>
<thead>
<tr>
<th><strong>Member</strong></th>
<th><strong>Description</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Delete(ElementId)</td>
<td>使用元素 ID 从项目中删除元素</td>
</tr>
<tr>
<td>Delete(<a target="_blank" rel="noopener" href="http://msdn2.microsoft.com/en-us/library/92t2ye13">ICollection</a>)</td>
<td>按元素的 ID 从项目中删除多个元素。</td>
</tr>
</tbody></table>
<p>第一种方法根据 Id 删除单个元素，如以下示例所示。</p>
<p>代码区域：根据 ElementId 删除元素</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">DeleteElement</span>(<span class="params">Autodesk.Revit.DB.Document document, Element element</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="comment">// Delete an element via its id</span></span><br><span class="line">        Autodesk.Revit.DB.ElementId elementId = element.Id;</span><br><span class="line">        ICollection&lt;Autodesk.Revit.DB.ElementId&gt; deletedIdSet = document.Delete(elementId);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">if</span> (<span class="number">0</span> == deletedIdSet.Count)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Deleting the selected element in Revit failed.&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        String prompt = <span class="string">&quot;The selected element has been removed and &quot;</span>;</span><br><span class="line">        prompt += deletedIdSet.Count - <span class="number">1</span>;</span><br><span class="line">        prompt += <span class="string">&quot; more dependent elements have also been removed.&quot;</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Give the user some information</span></span><br><span class="line">        TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, prompt);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>注意：删除元素时，与该元素关联的任何子元素也将被删除，如上面的示例所示。</p>
<p>该 API 还提供了一种删除多个元素的方法。</p>
<p>代码区域：根据 Id 删除多个元素</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// Delete all the selected elements via the set of elements</span></span><br><span class="line">UIDocument uidoc = <span class="keyword">new</span> UIDocument(document); </span><br><span class="line">ICollection elements = uidoc.Selection.GetElementIds();</span><br><span class="line">ICollection&lt;Autodesk.Revit.DB.ElementId&gt; deletedIdSet = document.Delete(elements);</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> (<span class="number">0</span> == deletedIdSet.Count)</span><br><span class="line">&#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Deleting the selected elements in Revit failed.&quot;</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,<span class="string">&quot;The selected element has been removed.&quot;</span>);</span><br></pre></td></tr></table></figure>

<p>注意：删除元素后，对已删除元素的任何引用都将无效，并在访问这些元素时引发异常。</p>
<h2 id="固定元素"><a href="#固定元素" class="headerlink" title="固定元素"></a>固定元素</h2><p>可以固定元素以防止它们移动。Element.Pinned 属性可用于检查元素是否已固定，或者固定或取消固定元素。</p>
<p>当 Element.Pinned 设置为 true 时，无法移动或旋转元素。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2>
    </div>
    
    
    
    
    
    
    
</div>

            <footer id="footer">
    <div id="footer-wrap">
        <div>
            &copy;
            2022 - 2024 funtim
            <span id="footer-icon">
                <i class="fa-solid fa-font-awesome fa-fw"></i>
            </span>
            &commat;John Doe
        </div>
        <div>
            Based on the <a target="_blank" rel="noopener" href="https://hexo.io">Hexo Engine</a> &amp;
            <a target="_blank" rel="noopener" href="https://github.com/theme-particlex/hexo-theme-particlex">ParticleX Theme</a>
        </div>
        
    </div>
</footer>

        </div>
        
        <transition name="fade">
            <div id="preview" ref="preview" v-show="previewShow">
                <img id="preview-content" ref="previewContent" />
            </div>
        </transition>
        
    </div>
    <script src="/js/main.js"></script>
    
    




    
</body>
</html>
