
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <title> | funtim</title>
    <meta name="author" content="XH" />
    <meta name="description" content="ddd" />
    <meta name="keywords" content="" />
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <link rel="icon" href="/images/avatar.jpg" />
    <link rel="preconnect" href="https://s4.zstatic.net" />
<script src="https://s4.zstatic.net/ajax/libs/vue/3.3.7/vue.global.prod.min.js"></script>
<link rel="stylesheet" href="https://s4.zstatic.net/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
<link rel="preconnect" href="https://fonts.googleapis.cn" />
<link rel="preconnect" href="https://fonts.gstatic.cn" crossorigin />
<link
    rel="stylesheet"
    href="https://fonts.googleapis.cn/css2?family=Fira+Code:wght@400;500;600;700&family=Lexend:wght@400;500;600;700;800;900&family=Noto+Sans+SC:wght@400;500;600;700;800;900&display=swap"
/>
<script> const mixins = {}; </script>

<script src="https://polyfill.alicdn.com/v3/polyfill.min.js?features=default"></script>


<script src="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="https://s4.zstatic.net/ajax/libs/highlightjs-line-numbers.js/2.8.0/highlightjs-line-numbers.min.js"></script>
<link
    rel="stylesheet"
    href="https://s4.zstatic.net/ajax/libs/highlight.js/11.9.0/styles/github.min.css"
/>
<script src="/js/lib/highlight.js"></script>



<script src="/js/lib/preview.js"></script>









<link rel="stylesheet" href="/css/main.css" />

<meta name="generator" content="Hexo 7.3.0"></head>
<body>
    <div id="layout">
        <transition name="fade">
            <div id="loading" v-show="loading">
                <div id="loading-circle">
                    <h2>LOADING</h2>
                    <p>加载过慢请开启缓存 浏览器默认开启</p>
                    <img src="/images/loading.gif" />
                </div>
            </div>
        </transition>
        <div id="menu" :class="{ hidden: hiddenMenu, 'menu-color': menuColor}">
    <nav id="desktop-menu">
        <a class="title" href="/">
            <span>FUNTIM</span>
        </a>
        
        <a href="/">
            <i class="fa-solid fa-house fa-fw"></i>
            <span>&ensp;Home</span>
        </a>
        
        <a href="/about">
            <i class="fa-solid fa-id-card fa-fw"></i>
            <span>&ensp;About</span>
        </a>
        
        <a href="/archives">
            <i class="fa-solid fa-box-archive fa-fw"></i>
            <span>&ensp;Archives</span>
        </a>
        
        <a href="/categories">
            <i class="fa-solid fa-bookmark fa-fw"></i>
            <span>&ensp;Categories</span>
        </a>
        
        <a href="/tags">
            <i class="fa-solid fa-tags fa-fw"></i>
            <span>&ensp;Tags</span>
        </a>
        
    </nav>
    <nav id="mobile-menu">
        <div class="title" @click="showMenuItems = !showMenuItems">
            <i class="fa-solid fa-bars fa-fw"></i>
            <span>&emsp;FUNTIM</span>
        </div>
        <transition name="slide">
            <div class="items" v-show="showMenuItems">
                
                <a href="/">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-house fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Home</div>
                    </div>
                </a>
                
                <a href="/about">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-id-card fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">About</div>
                    </div>
                </a>
                
                <a href="/archives">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-box-archive fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Archives</div>
                    </div>
                </a>
                
                <a href="/categories">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-bookmark fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Categories</div>
                    </div>
                </a>
                
                <a href="/tags">
                    <div class="item">
                        <div style="min-width: 20px; max-width: 50px; width: 10%">
                            <i class="fa-solid fa-tags fa-fw"></i>
                        </div>
                        <div style="min-width: 100px; max-width: 150%; width: 20%">Tags</div>
                    </div>
                </a>
                
            </div>
        </transition>
    </nav>
</div>
<transition name="fade">
    <div id="menu-curtain" @click="showMenuItems = !showMenuItems" v-show="showMenuItems"></div>
</transition>

        <div id="main" :class="loading ? 'into-enter-from': 'into-enter-active'">
            <div class="article">
    <div>
        <h1></h1>
    </div>
    <div class="info">
        <span class="date">
            <span class="icon">
                <i class="fa-solid fa-calendar fa-fw"></i>
            </span>
            2024/12/28
        </span>
        
        
    </div>
    
    <div class="content" v-pre>
        <h1 id="建筑"><a href="#建筑" class="headerlink" title="建筑"></a>建筑</h1><p>本章介绍特定于Revit建筑功能的API功能：</p>
<ul>
<li>与房间相关的功能（Element.Room、RoomTag等）</li>
</ul>
<p> 本节中的主题</p>
<ul>
<li>Rooms</li>
</ul>
<h2 id="房间"><a href="#房间" class="headerlink" title="房间"></a>房间</h2><p><strong>Rooms</strong> </p>
<p>以下各节介绍了有关房间类、其参数以及如何在API中使用房间类的信息。</p>
<p>Room类用于表示房间和图元，例如房间明细表和面积平面。下表列出了API中不同房间、面积及其对应标签的属性和创建函数：</p>
<p><strong>表55：房间、面积和标签关系</strong></p>
<table>
<thead>
<tr>
<th>**Element **</th>
<th>**Class **</th>
<th>**Category **</th>
<th>**Boundary **</th>
<th>**Location **</th>
<th>**Can Create **</th>
</tr>
</thead>
<tbody><tr>
<td>Room in Plan View</td>
<td>Room</td>
<td>OST_Rooms</td>
<td>在封闭区域中有</td>
<td>LocationPoint</td>
<td>NewRoom（），NewRoom（Phase）除外</td>
</tr>
<tr>
<td>Room in Schedule View</td>
<td>Room</td>
<td>OST_Rooms</td>
<td>Null</td>
<td>Null</td>
<td>NewRoom(Phase)</td>
</tr>
<tr>
<td>Area</td>
<td>Room</td>
<td>OST_Areas</td>
<td>总是有</td>
<td>LocationPoint</td>
<td>No</td>
</tr>
<tr>
<td>Room Tag</td>
<td>RoomTag</td>
<td>OST_RoomTags</td>
<td></td>
<td>LocationPoint</td>
<td>Creation.Document.NewRoomTag()</td>
</tr>
<tr>
<td>Area Tag</td>
<td>FamilySymbol</td>
<td>OST_AreaTags</td>
<td></td>
<td>LocationPoint</td>
<td>No</td>
</tr>
</tbody></table>
<p>注：房间名称是房间名称和房间号的组合。例如，对于编号为2且名称为“Master Bedroom”的房间，Room.Name将返回“Master Bedroom 2”。使用ROOM_NAME内置参数获取房间名称。</p>
<p>注意：作为注释元素，特定视图可使用RoomTag. View。不要尝试设置RoomTag.Name属性，因为该名称是自动分配的;否则将引发异常。</p>
<p><strong>创建房间</strong></p>
<p>下面的代码演示了在特定楼层的某个点创建房间的最简单方法：</p>
<p>代码区域28-1：创建房间</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">Room <span class="title">CreateRoom</span>(<span class="params">Autodesk.Revit.DB.Document document, Level level</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        <span class="comment">// Create a UV structure which determines the room location</span></span><br><span class="line">        UV roomLocation = <span class="keyword">new</span> UV(<span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Create a new room</span></span><br><span class="line">        Room room = document.Create.NewRoom(level, roomLocation);</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> == room)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Create a new room failed.&quot;</span>);</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">return</span> room;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>可以在房间明细表中创建房间，然后将其插入到平面回路中。</p>
<ul>
<li>Document.NewRoom（Phase）方法用于创建不与任何特定位置关联的新文件室，并将其插入到现有明细表中。在拨打电话之前，确保房间时间表存在或在指定阶段创建房间时间表。</li>
<li>Document.NewRoom（Roomroom，PlanCircuit线路）方法用于从明细表中的房间和PlanCircuit创建房间。<ul>
<li>输入房间必须仅存在于房间明细表中，这意味着它不会显示在任何平面视图中。</li>
<li>调用该方法后，将在PlanCircuit所在的视图中创建具有相同名称和编号的模型房间。</li>
</ul>
</li>
</ul>
<p>有关平面电路的详细信息，请参见平面拓扑。</p>
<p>以下代码说明了整个过程：</p>
<p>代码区域28-2：创建房间并将其插入到平面回路中</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">Room <span class="title">InsertNewRoomInPlanCircuit</span>(<span class="params">Autodesk.Revit.DB.Document document, Level level, Phase newConstructionPhase</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// create room using Phase</span></span><br><span class="line">    Room newScheduleRoom = document.Create.NewRoom(newConstructionPhase);</span><br><span class="line">            </span><br><span class="line">    <span class="comment">// set the Room Number and Name</span></span><br><span class="line">    <span class="built_in">string</span> newRoomNumber = <span class="string">&quot;101&quot;</span>;</span><br><span class="line">    <span class="built_in">string</span> newRoomName = <span class="string">&quot;Class Room 1&quot;</span>;</span><br><span class="line">    newScheduleRoom.Name = newRoomName;</span><br><span class="line">    newScheduleRoom.Number = newRoomNumber;</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Get a PlanCircuit</span></span><br><span class="line">    PlanCircuit planCircuit = <span class="literal">null</span>;</span><br><span class="line">    <span class="comment">// first get the plan topology for given level</span></span><br><span class="line">    PlanTopology planTopology = document.get_PlanTopology(level);</span><br><span class="line">            </span><br><span class="line">    <span class="comment">// Iterate circuits in this plan topology</span></span><br><span class="line">    <span class="keyword">foreach</span> (PlanCircuit circuit <span class="keyword">in</span> planTopology.Circuits)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// get the first circuit we find</span></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != circuit)</span><br><span class="line">        &#123;</span><br><span class="line">            planCircuit = circuit;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">           </span><br><span class="line">    Room newRoom2 = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != planCircuit)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Create Room&quot;</span>))</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="keyword">if</span> (transaction.Start() == TransactionStatus.Started)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="comment">// The input room must exist only in the room schedule, </span></span><br><span class="line">                <span class="comment">// meaning that it does not display in any plan view.</span></span><br><span class="line">                newRoom2 = document.Create.NewRoom(newScheduleRoom, planCircuit);</span><br><span class="line">                <span class="comment">// a model room with the same name and number is created in the </span></span><br><span class="line">                <span class="comment">// view where the PlanCircuit is located</span></span><br><span class="line">                <span class="keyword">if</span> (<span class="literal">null</span> != newRoom2)</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="comment">// Give the user some information</span></span><br><span class="line">                    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, <span class="string">&quot;Room placed in Plan Circuit successfully.&quot;</span>);</span><br><span class="line">                &#125;</span><br><span class="line">                transaction.Commit();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> newRoom2;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>创建房间并将其添加到位置后，可以使用Room.Unplace（）方法将其从该位置删除（但在项目中仍然可用）。然后可以将其放置在新的位置。</p>
<h3 id="房间边界"><a href="#房间边界" class="headerlink" title="房间边界"></a>房间边界</h3><p>房间的边界可在房间所在的位置创建封闭区域。</p>
<ul>
<li>边界包括以下要素：<ul>
<li>Walls  </li>
<li>Model lines  </li>
<li>Columns  </li>
<li>Roofs</li>
</ul>
</li>
</ul>
<h4 id="检索房间边界"><a href="#检索房间边界" class="headerlink" title="检索房间边界"></a>检索房间边界</h4><p>房间周围的边界是从基类方法SpatialElement.GetBoundarySegments（）获得的。当房间不在封闭区域中或仅存在于明细表中时，该方法返回null。每个房间可能有几个区域，每个区域都有几个段，因此数据以BoundarySegment列表的形式返回。</p>
<p>下图显示了在Revit UI中选择的房间边界：</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-4FEC99FB-5F16-4343-8475-ECFF367CB072.png" alt="img"></p>
<p>图138：房间边界</p>
<p>线段列表的大小取决于封闭区域拓扑。每个BoundarySegment列表都创建一个回路或一条连续的线，其中一个线段连接到下一个线段。下面的图片提供了几个例子。在下面的图片中，所有墙都是“房间边界”，模型线类别为OST_AreaSeparationLines。如果某个图元不是“房间边界”，则将其从图元中排除以形成边界。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-792A1532-E1EE-4186-894F-F593C930B2A6.png" alt="img"></p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-C259DDE9-9A9E-457F-87C3-3D686A8A9359.png"></p>
<p>下表提供了之前房间的Room.GetBoundarySegments（）.Size结果：</p>
<p><strong>表56：Room.GetBoundarySegments（）.Size</strong></p>
<table>
<thead>
<tr>
<th><strong>Room 房间</strong></th>
<th>**Room.GetBoundarySegments().Size **</th>
</tr>
</thead>
<tbody><tr>
<td>Room 1、2、3</td>
<td>1</td>
</tr>
<tr>
<td>Room 4</td>
<td>2</td>
</tr>
<tr>
<td>Room 5、6</td>
<td>3</td>
</tr>
</tbody></table>
<p>注意：由模型线连接的墙被视为连续的线段。单个模型线将被忽略。</p>
<p>获取IList&lt;IList<BoundarySegment>后，通过迭代列表获取BoundarySegment。</p>
<p><strong>BoundarySegment</strong> </p>
<p>构成区域的线段由BoundarySegment类表示;其ElementId属性返回对应元素的id，条件如下：</p>
<ul>
<li>对于ModelCurve元素，类别必须是BuiltInCategory.OST_AreaSeparationLines，这意味着它表示房间分隔符。</li>
<li>对于墙、柱和屋顶等其他图元，如果图元是房间边界，则“房间边界”参数（BuiltInParameter.WALL_ATTR_ROOM_BOUNDING）必须为真，如下图所示。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-FBC69AE1-EF76-4773-AC4A-7CBCC77EE924.png" alt="img"></p>
<p>图141：房间边界属性</p>
<p>WALL_ATTR_ROOM_BOUNDING内置参数通过API设置：</p>
<p>代码区域28-3：设置房间边界</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">SetRoomBounding</span>(<span class="params">Wall wall</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Parameter parameter = wall.get_Parameter(BuiltInParameter.WALL_ATTR_ROOM_BOUNDING);</span><br><span class="line">        parameter.Set(<span class="number">1</span>);   <span class="comment">//set &quot;Room Bounding&quot; to true</span></span><br><span class="line">        parameter.Set(<span class="number">0</span>);   <span class="comment">//set &quot;Room Bounding&quot; to false</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>请注意，在下面的图片中，屋顶如何形成房间的BoundarySegment。第一张图片显示立面视图中的Level 3。将在Level 3楼层视图中创建房间。后两张图片显示了房间和房子的3D视图的边界。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-067191A0-12EA-430F-B145-6B8D5D6E596E.png" alt="img"></p>
<p>图142：在标高3视图中创建的房间</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-862FFB79-21A7-4F5A-B949-B442529EF50E.png"></p>
<p><strong>图143：</strong>屋顶形成的房间边界</p>
<p>面积边界只能是类别为面积边界（BuiltInCategory.OST_AreaSchemeLines）的ModelCurve，而显示房间的边界可以是墙和其他图元。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-8B918B3C-ED10-486C-912A-9D4A1F8CC4EA.png"></p>
<p>图144：墙端边缘</p>
<p>如果BoundarySegment对应于房间分隔和墙之间的曲线，如上图所示：</p>
<ul>
<li>Element属性返回null</li>
<li>曲线不为空。</li>
</ul>
<p><strong>边界与事务</strong></p>
<p>在使用API创建了一个元素（如墙）之后，如果调用Room.GetBoundarySegments（），墙可以更改房间边界。您必须确保数据已更新。</p>
<p>下图显示了使用Revit Platform API创建墙后房间的变化。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-5410C3CF-324E-4C38-9152-BA29AB5D6CA1.png" alt="img"></p>
<p>图145：添加的墙更改房间边界</p>
<p>要更新房间边界数据，请使用以下代码中的事务机制：</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">UpdateRoomBoundary</span>(<span class="params">UIApplication application, Room room, Level level</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Document document = application.ActiveUIDocument.Document;</span><br><span class="line">            </span><br><span class="line">    <span class="comment">//Get the size before creating a wall</span></span><br><span class="line">    <span class="built_in">int</span> size = room.GetBoundarySegments(<span class="keyword">new</span> SpatialElementBoundaryOptions()).First().Count;</span><br><span class="line">    <span class="built_in">string</span> message = <span class="string">&quot;Room boundary size before wall: &quot;</span> + size;</span><br><span class="line"></span><br><span class="line">    <span class="comment">//Prepare a line</span></span><br><span class="line">    XYZ startPos = <span class="keyword">new</span> XYZ(<span class="number">-10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    XYZ endPos = <span class="keyword">new</span> XYZ(<span class="number">10</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    Line line = Line.CreateBound(startPos, endPos);</span><br><span class="line"></span><br><span class="line">    <span class="comment">//Create a new wall and enclose the creating into a single transaction</span></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Create Wall&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (transaction.Start() == TransactionStatus.Started)</span><br><span class="line">        &#123;</span><br><span class="line">            Wall wall = Wall.Create(document, line, level.Id, <span class="literal">false</span>);</span><br><span class="line">            <span class="keyword">if</span> (<span class="literal">null</span> != wall)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">if</span> (TransactionStatus.Committed == transaction.Commit())</span><br><span class="line">                &#123;</span><br><span class="line">                    <span class="comment">//Get the new size</span></span><br><span class="line">                    size = room.GetBoundarySegments(<span class="keyword">new</span> SpatialElementBoundaryOptions()).First().Count;</span><br><span class="line">                    message += <span class="string">&quot;\nRoom boundary size after wall: &quot;</span> + size;</span><br><span class="line">                    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>, message);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">else</span></span><br><span class="line">            &#123;</span><br><span class="line">                transaction.RollBack();</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>有关详细信息，请参阅事务。</p>
<p><strong>平面拓扑</strong></p>
<p>房间所在的标高平面具有由墙和房间分隔线等图元构成的拓扑。PlanTopology和PlanCircuit类用于表示标高拓扑。</p>
<ul>
<li>使用Level从Document对象获取PlanTopology对象。在每个平面视图中，每个阶段对应一个PlanTopology。</li>
<li>相同的条件适用于BoundarySegment，但房间分隔符和房间边界参数为true的元素可以是PlanCircuit中的边（边界）。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-E0715B88-5A70-4424-8268-E1CAD3D5EEFF.png" alt="img"></p>
<p>图146：房间和平面拓扑图</p>
<p>PlanCircuit.Sideship属性返回线路边编号，而SpatialElement.GetBoundarySegments（）返回IList&lt;IList&lt;Autodesk.Revit.DB.BoundarySegment&gt;，其Count与线路边编号不同。</p>
<ul>
<li>如果墙上有分支，则SpatialElement.GetBoundarySegments（）将底墙识别为两面墙。</li>
<li>PlanCircuit.无论分支的数量如何，Sideball总是将图片中的底墙视为一个。</li>
</ul>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-25504A29-2C29-409B-AFF6-916CD359E8C2.png" alt="img"></p>
<p>图147：比较房间边界与PlanCircuit</p>
<p>表57：房间边界与平面回路的比较</p>
<table>
<thead>
<tr>
<th>**Circuit **</th>
<th><strong>Circuit.SideNum</strong></th>
<th>**IList&lt;IList&lt;Autodesk.Revit.DB.BoundarySegment&gt; .Count for Room **</th>
</tr>
</thead>
<tbody><tr>
<td>Circuit 1</td>
<td>3</td>
<td>3 (Room1)</td>
</tr>
<tr>
<td>Circuit 2</td>
<td>4 +2 &#x3D; 6</td>
<td>4 +3 &#x3D; 7 (Room2)</td>
</tr>
<tr>
<td>Circuit 3</td>
<td>3 +2 &#x3D; 5</td>
<td>3 +3 &#x3D; 6 (Room3)</td>
</tr>
<tr>
<td>Circuit 4</td>
<td>3</td>
<td>3 (Room4)</td>
</tr>
<tr>
<td>Circuit 5</td>
<td>3</td>
<td>3 (Room5)</td>
</tr>
</tbody></table>
<p><strong>房间和族实例</strong></p>
<p>“门”和“窗”是与“房间”相关的特殊族实例。这里只讨论门，因为唯一的区别是窗户没有翻转把手。</p>
<p>以下特性适用于门：</p>
<ul>
<li>门元素可以在没有房间的情况下存在。</li>
<li>在API中（仅在API中），Door元素具有两个附加属性，它们引用门的两个相对侧上的区域：ToRoom和FromRoom</li>
<li>如果区域是房间，则属性的值将是房间元素。</li>
<li>如果区域不是房间，则属性将返回null。两个属性可以同时为null。</li>
<li>门打开的一侧的区域将是ToRoom。另一边的房间将是FromRoom。</li>
<li>每当相应的区域发生变化时，这两个属性都会动态更新。</li>
</ul>
<p>在下面的图片中，五扇门插入到墙中，而不翻转饰面。该表列出了每个门的FromRoom、ToRoom和Room属性。房间属性属于所有族实例。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-B05F86CE-DD91-401E-BD6C-67704F9BE55C.png" alt="img"></p>
<p>Figure 148: Door 1 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-4D623C2A-40AC-44D0-86E5-14D00C649014.png" alt="img"></p>
<p>Figure 149: Door 2 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-97032EDC-973A-4DD0-A314-3796F3E52F1E.png" alt="img"></p>
<p>Figure 150: Door 3 </p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-25B7F1B6-3F62-4607-A2DC-AA38B4CBE0D1.png" alt="img"></p>
<p>Figure 151: Door 4</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-BEB8BE84-3D6F-4E7E-A87D-0FE6C7CB6D3F.png" alt="img"></p>
<p>Figure 152: Door 5 </p>
<p><strong>表58：门属性</strong></p>
<table>
<thead>
<tr>
<th>**Door **</th>
<th><strong>FromRoom</strong></th>
<th><strong>ToRoom</strong></th>
<th><strong>Room 房间</strong></th>
</tr>
</thead>
<tbody><tr>
<td>Door 1</td>
<td>null</td>
<td>null</td>
<td>null</td>
</tr>
<tr>
<td>Door 2</td>
<td>Room 1</td>
<td>null</td>
<td>null</td>
</tr>
<tr>
<td>Door 3</td>
<td>Room 3</td>
<td>Room 2</td>
<td>Room 2</td>
</tr>
<tr>
<td>Door 4</td>
<td>Room 4</td>
<td>null</td>
<td>null</td>
</tr>
<tr>
<td>Door 5</td>
<td>null</td>
<td>Room 6</td>
<td>Room 6</td>
</tr>
</tbody></table>
<p>所有族实例都具有“房间”属性，该属性是实例在上一个项目阶段中所在的房间。窗户和门都面对着一个房间。通过翻转门或窗的朝向或调用FamilyInstance.FlipFromToRoom（）来更改房间。对于其他类型的实例（如梁和柱），“房间”是与实例具有相同边界的房间。</p>
<p>下面的代码演示了如何从族实例中获取Room。需要检查结果是否为null。</p>
<p>代码区域28-5：从族实例获取房间</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetRoomInfo</span>(<span class="params">FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">        Room room = familyInstance.Room;</span><br><span class="line">        room = familyInstance.FromRoom;  <span class="comment">//for door and window family only</span></span><br><span class="line">        room = familyInstance.ToRoom;    <span class="comment">//for door and window family only</span></span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != room)</span><br><span class="line">        &#123;</span><br><span class="line">                <span class="comment">//use the room...</span></span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>其他房间属性</strong></p>
<p>Room类还有其他几个属性，可用于获取有关对象的信息。房间具有以下只读尺寸属性：</p>
<ul>
<li>Area  </li>
<li>Perimeter </li>
<li>UnboundedHeight</li>
<li>Volume  </li>
<li>ClosedShell</li>
</ul>
<p>此示例显示选定房间的尺寸标注信息。请注意，必须启用体积计算设置，否则房间体积将返回为0。</p>
<p>代码区域28-6：获取房间的尺寸</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetRoomDimensions</span>(<span class="params">Document doc, Room room</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    String roominfo = <span class="string">&quot;Room dimensions:\n&quot;</span>;</span><br><span class="line">    <span class="comment">// turn on volume calculations:</span></span><br><span class="line">    <span class="keyword">using</span> (Transaction t = <span class="keyword">new</span> Transaction(doc, <span class="string">&quot;Turn on volume calculation&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        t.Start();</span><br><span class="line">        AreaVolumeSettings settings = AreaVolumeSettings.GetAreaVolumeSettings(doc);</span><br><span class="line">        settings.ComputeVolumes = <span class="literal">true</span>;</span><br><span class="line">        t.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">            </span><br><span class="line">    roominfo += <span class="string">&quot;Vol: &quot;</span> + room.Volume + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    roominfo += <span class="string">&quot;Area: &quot;</span> + room.Area + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    roominfo += <span class="string">&quot;Perimeter: &quot;</span> + room.Perimeter + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    roominfo += <span class="string">&quot;Unbounded height: &quot;</span> + room.UnboundedHeight + <span class="string">&quot;\n&quot;</span>;</span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,roominfo);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>房间（或空间）的ClosedShell属性是由房间开放空间的边界（墙、楼板、天花板、屋顶和边界线）形成的几何图形。如果需要检查模型中的其他物理图元与房间的交点，例如，查看图元的一部分或全部是否位于房间中，则此属性非常有用。有关示例，请参见随Revit SDK提供的RoofsRooms示例应用程序，其中ClosedShell用于检查房间是否垂直无边界。</p>
<p>此外，还可以获取或设置具有以下属性的房间的基准偏移和限制偏移：</p>
<ul>
<li>BaseOffset</li>
<li>LimitOffset</li>
</ul>
<p>可以使用UpperLimit属性获取或设置定义房间上限的标高。</p>
<h2 id="注：翻译自Revit-API-Developers-Guide"><a href="#注：翻译自Revit-API-Developers-Guide" class="headerlink" title="注：翻译自Revit API Developers Guide"></a><em><strong>注：</strong></em>翻译自<a target="_blank" rel="noopener" href="https://help.autodesk.com/view/RVT/2018/ENU/?guid=Revit_API_Revit_API_Developers_Guide_html">Revit API Developers Guide</a></h2>
    </div>
    
    
    
    
    
    
    
</div>

            <footer id="footer">
    <div id="footer-wrap">
        <div>
            &copy;
            2022 - 2024 funtim
            <span id="footer-icon">
                <i class="fa-solid fa-font-awesome fa-fw"></i>
            </span>
            &commat;XH
        </div>
        <div>
            Based on the <a target="_blank" rel="noopener" href="https://hexo.io">Hexo Engine</a> &amp;
            <a target="_blank" rel="noopener" href="https://github.com/theme-particlex/hexo-theme-particlex">ParticleX Theme</a>
        </div>
        
    </div>
</footer>

        </div>
        
        <transition name="fade">
            <div id="preview" ref="preview" v-show="previewShow">
                <img id="preview-content" ref="previewContent" />
            </div>
        </transition>
        
    </div>
    <script src="/js/main.js"></script>
    
    




    
</body>
</html>
