<!DOCTYPE html><html lang="zh-CN" data-theme="light"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0,viewport-fit=cover"><title>26结构工程 | funtim的博客</title><meta name="author" content="funtim41@gmail.com"><meta name="copyright" content="funtim41@gmail.com"><meta name="format-detection" content="telephone=no"><meta name="theme-color" content="#ffffff"><meta name="description" content="结构工程以下各节介绍了仅与Revit的结构工程功能相关的API功能：  结构模型元素-讨论仅与Revit的结构工程功能相关的特定元素及其属性。  AnalyticalModel -讨论与分析模型相关的类，如AnalyticalModel、RigidLink和AnalyticalModelSupport。  AnalyticalLink -讨论在分析梁和柱之间创建新的分析链接。  荷载-讨论荷载设置">
<meta property="og:type" content="article">
<meta property="og:title" content="26结构工程">
<meta property="og:url" content="https://funtim41.github.io/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/26%E7%BB%93%E6%9E%84%E5%B7%A5%E7%A8%8B/">
<meta property="og:site_name" content="funtim的博客">
<meta property="og:description" content="结构工程以下各节介绍了仅与Revit的结构工程功能相关的API功能：  结构模型元素-讨论仅与Revit的结构工程功能相关的特定元素及其属性。  AnalyticalModel -讨论与分析模型相关的类，如AnalyticalModel、RigidLink和AnalyticalModelSupport。  AnalyticalLink -讨论在分析梁和柱之间创建新的分析链接。  荷载-讨论荷载设置">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://funtim41.github.io/images/4stars.png">
<meta property="article:published_time" content="2024-12-28T13:19:50.000Z">
<meta property="article:modified_time" content="2024-12-28T13:19:57.724Z">
<meta property="article:author" content="funtim41@gmail.com">
<meta property="article:tag" content="Revit二次开发人员指南">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://funtim41.github.io/images/4stars.png"><link rel="shortcut icon" href="/images/OIP.jfif"><link rel="canonical" href="https://funtim41.github.io/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/26%E7%BB%93%E6%9E%84%E5%B7%A5%E7%A8%8B/"><link rel="preconnect" href="//cdn.jsdelivr.net"/><link rel="preconnect" href="//busuanzi.ibruce.info"/><link rel="stylesheet" href="/css/index.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css" media="print" onload="this.media='all'"><script>
    (() => {
      
    const saveToLocal = {
      set: (key, value, ttl) => {
        if (!ttl) return
        const expiry = Date.now() + ttl * 86400000
        localStorage.setItem(key, JSON.stringify({ value, expiry }))
      },
      get: key => {
        const itemStr = localStorage.getItem(key)
        if (!itemStr) return undefined
        const { value, expiry } = JSON.parse(itemStr)
        if (Date.now() > expiry) {
          localStorage.removeItem(key)
          return undefined
        }
        return value
      }
    }

    window.btf = {
      saveToLocal,
      getScript: (url, attr = {}) => new Promise((resolve, reject) => {
        const script = document.createElement('script')
        script.src = url
        script.async = true
        Object.entries(attr).forEach(([key, val]) => script.setAttribute(key, val))
        script.onload = script.onreadystatechange = () => {
          if (!script.readyState || /loaded|complete/.test(script.readyState)) resolve()
        }
        script.onerror = reject
        document.head.appendChild(script)
      }),
      getCSS: (url, id) => new Promise((resolve, reject) => {
        const link = document.createElement('link')
        link.rel = 'stylesheet'
        link.href = url
        if (id) link.id = id
        link.onload = link.onreadystatechange = () => {
          if (!link.readyState || /loaded|complete/.test(link.readyState)) resolve()
        }
        link.onerror = reject
        document.head.appendChild(link)
      }),
      addGlobalFn: (key, fn, name = false, parent = window) => {
        if (!false && key.startsWith('pjax')) return
        const globalFn = parent.globalFn || {}
        globalFn[key] = globalFn[key] || {}
        globalFn[key][name || Object.keys(globalFn[key]).length] = fn
        parent.globalFn = globalFn
      }
    }
  
      
      const activateDarkMode = () => {
        document.documentElement.setAttribute('data-theme', 'dark')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#0d0d0d')
        }
      }
      const activateLightMode = () => {
        document.documentElement.setAttribute('data-theme', 'light')
        if (document.querySelector('meta[name="theme-color"]') !== null) {
          document.querySelector('meta[name="theme-color"]').setAttribute('content', '#ffffff')
        }
      }

      btf.activateDarkMode = activateDarkMode
      btf.activateLightMode = activateLightMode

      const theme = saveToLocal.get('theme')
    
          theme === 'dark' ? activateDarkMode() : theme === 'light' ? activateLightMode() : null
        
      
      const asideStatus = saveToLocal.get('aside-status')
      if (asideStatus !== undefined) {
        document.documentElement.classList.toggle('hide-aside', asideStatus === 'hide')
      }
    
      
    const detectApple = () => {
      if (/iPad|iPhone|iPod|Macintosh/.test(navigator.userAgent)) {
        document.documentElement.classList.add('apple')
      }
    }
    detectApple()
  
    })()
  </script><script>const GLOBAL_CONFIG = {
  root: '/',
  algolia: undefined,
  localSearch: {"path":"/search.xml","preload":false,"top_n_per_article":1,"unescape":false,"languages":{"hits_empty":"未找到符合您查询的内容：${query}","hits_stats":"共找到 ${hits} 篇文章"}},
  translate: undefined,
  highlight: {"plugin":"highlight.js","highlightCopy":true,"highlightLang":true,"highlightHeightLimit":false,"highlightFullpage":false,"highlightMacStyle":false},
  copy: {
    success: '复制成功',
    error: '复制失败',
    noSupport: '浏览器不支持'
  },
  relativeDate: {
    homepage: false,
    post: false
  },
  runtime: '',
  dateSuffix: {
    just: '刚刚',
    min: '分钟前',
    hour: '小时前',
    day: '天前',
    month: '个月前'
  },
  copyright: {"limitCount":150,"languages":{"author":"作者: funtim41@gmail.com","link":"链接: ","source":"来源: funtim的博客","info":"著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"}},
  lightbox: 'null',
  Snackbar: {"chs_to_cht":"已切换为繁体中文","cht_to_chs":"已切换为简体中文","day_to_night":"已切换为深色模式","night_to_day":"已切换为浅色模式","bgLight":"#49b1f5","bgDark":"#1f1f1f","position":"bottom-left"},
  infinitegrid: {
    js: 'https://cdn.jsdelivr.net/npm/@egjs/infinitegrid/dist/infinitegrid.min.js',
    buttonText: '加载更多'
  },
  isPhotoFigcaption: false,
  islazyload: false,
  isAnchor: true,
  percent: {
    toc: true,
    rightside: true,
  },
  autoDarkmode: false
}</script><script id="config-diff">var GLOBAL_CONFIG_SITE = {
  title: '26结构工程',
  isPost: true,
  isHome: false,
  isHighlightShrink: false,
  isToc: true,
  isShuoshuo: false
}</script><meta name="generator" content="Hexo 7.3.0"></head><body><div id="web_bg" style="background: Color(#995a82);"></div><div id="sidebar"><div id="menu-mask"></div><div id="sidebar-menus"><div class="avatar-img text-center"><img src="/images/4stars.png" onerror="onerror=null;src='/img/friend_404.gif'" alt="avatar"/></div><div class="site-data text-center"><a href="/archives/"><div class="headline">文章</div><div class="length-num">32</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">1</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">1</div></a></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div></div></div><div class="post" id="body-wrap"><header class="post-bg fixed" id="page-header" style="background-image: url(/images/topback.jpg);"><nav id="nav"><span id="blog-info"><a class="nav-site-title" href="/"><img class="site-icon" src="/images/OIP.jfif" alt="Logo"><span class="site-name">funtim的博客</span></a><a class="nav-page-title" href="/"><span class="site-name">26结构工程</span></a></span><div id="menus"><div id="search-button"><span class="site-page social-icon search"><i class="fas fa-search fa-fw"></i><span> 搜索</span></span></div><div class="menus_items"><div class="menus_item"><a class="site-page" href="/"><i class="fa-fw fas fa-home"></i><span> Home</span></a></div><div class="menus_item"><a class="site-page" href="/archives/"><i class="fa-fw fas fa-archive"></i><span> Timeline</span></a></div><div class="menus_item"><a class="site-page" href="/tags/"><i class="fa-fw fas fa-tags"></i><span> Tags</span></a></div><div class="menus_item"><a class="site-page" href="/categories/"><i class="fa-fw fas fa-folder-open"></i><span> Categories</span></a></div><div class="menus_item"><a class="site-page" href="/Links/"><i class="fa-fw fas fa-link"></i><span> Links</span></a></div><div class="menus_item"><a class="site-page" href="/about/"><i class="fa-fw fas fa-heart"></i><span> About</span></a></div></div><div id="toggle-menu"><span class="site-page"><i class="fas fa-bars fa-fw"></i></span></div></div></nav><div id="post-info"><h1 class="post-title">26结构工程</h1><div id="post-meta"><div class="meta-firstline"><span class="post-meta-date"><i class="far fa-calendar-alt fa-fw post-meta-icon"></i><span class="post-meta-label">发表于</span><time class="post-meta-date-created" datetime="2024-12-28T13:19:50.000Z" title="发表于 2024-12-28 21:19:50">2024-12-28</time><span class="post-meta-separator">|</span><i class="fas fa-history fa-fw post-meta-icon"></i><span class="post-meta-label">更新于</span><time class="post-meta-date-updated" datetime="2024-12-28T13:19:57.724Z" title="更新于 2024-12-28 21:19:57">2024-12-28</time></span></div><div class="meta-secondline"><span class="post-meta-separator">|</span><span class="post-meta-pv-cv" id="" data-flag-title=""><i class="far fa-eye fa-fw post-meta-icon"></i><span class="post-meta-label">浏览量:</span><span id="busuanzi_value_page_pv"><i class="fa-solid fa-spinner fa-spin"></i></span></span></div></div></div></header><main class="layout" id="content-inner"><div id="post"><article class="container post-content" id="article-container"><h1 id="结构工程"><a href="#结构工程" class="headerlink" title="结构工程"></a>结构工程</h1><p>以下各节介绍了仅与Revit的结构工程功能相关的API功能：</p>
<ul>
<li><p>结构模型元素-讨论仅与Revit的结构工程功能相关的特定元素及其属性。</p>
</li>
<li><p>AnalyticalModel -讨论与分析模型相关的类，如AnalyticalModel、RigidLink和AnalyticalModelSupport。</p>
</li>
<li><p>AnalyticalLink -讨论在分析梁和柱之间创建新的分析链接。</p>
</li>
<li><p>荷载-讨论荷载设置和三种荷载。</p>
</li>
</ul>
<p>您的分析链接-为希望将Revit链接到某些Structural Analysis应用程序的API用户提供建议。</p>
<p>本章包含一些高级主题。如果您不熟悉Revit Platform API，请先阅读基本部分，如“入门”、“元素要素”、“参数”等。</p>
<ul>
<li>本节中的主题<ul>
<li>结构模型元素</li>
<li>分析模型<br>在结构工程中，分析模型是结构物理模型的工程描述。</li>
<li>荷载<br>以下部分确定荷载设置并讨论荷载限制指南。</li>
<li>Analysis Link分析链接</li>
<li>Analytical Links</li>
</ul>
</li>
</ul>
<h2 id="结构模型元素"><a href="#结构模型元素" class="headerlink" title="结构模型元素"></a>结构模型元素</h2><p>结构模型元素实际上是支撑结构的元素，如柱、钢筋、桁架等。以下部分介绍如何操作这些元素。</p>
<p>本节中包含的模型元素特定于Revit的结构工程功能。有关其他结构元素类的详细信息，请参见“墙、楼板、屋顶和洞口”和“族”中的相应部分。</p>
<p>本节中的主题</p>
<ul>
<li>结构柱、梁和支撑</li>
<li>桁架</li>
<li>加强<br>Revit API提供了用于管理有效主体（如混凝土柱、梁、墙、基础和结构楼板）中的钢筋（如钢筋、钢筋或钢筋网）的类。</li>
<li>边界条件</li>
<li>板</li>
</ul>
<h3 id="结构柱、梁和支撑"><a href="#结构柱、梁和支撑" class="headerlink" title="结构柱、梁和支撑"></a>结构柱、梁和支撑</h3><p><strong>结构柱、梁和支撑</strong></p>
<p>结构柱、梁和支撑元素都由FamilyInstance类表示。它们由StructuralType属性区分。</p>
<p>代码区域29-1：柱、梁和支撑的区别</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetStructuralType</span>(<span class="params">FamilyInstance familyInstance</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="built_in">string</span> message = <span class="string">&quot;&quot;</span>;</span><br><span class="line">    <span class="keyword">switch</span> (familyInstance.StructuralType)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">case</span> StructuralType.Beam:</span><br><span class="line">            message = <span class="string">&quot;FamilyInstance is a beam.&quot;</span>;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        <span class="keyword">case</span> StructuralType.Brace:</span><br><span class="line">            message = <span class="string">&quot;FamilyInstance is a brace.&quot;</span>;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        <span class="keyword">case</span> StructuralType.Column:</span><br><span class="line">            message = <span class="string">&quot;FamilyInstance is a column.&quot;</span>;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        <span class="keyword">case</span> StructuralType.Footing:</span><br><span class="line">            message = <span class="string">&quot;FamilyInstance is a footing.&quot;</span>;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">        <span class="literal">default</span>:</span><br><span class="line">            message = <span class="string">&quot;FamilyInstance is non-structural or unknown framing.&quot;</span>;</span><br><span class="line">            <span class="keyword">break</span>;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,message);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>可以使用类别过滤出与结构柱、梁和支撑对应的FamilySymbol对象。结构梁和支撑的类别为BuiltInCategory.OST_StructuralFraming。结构柱的类别为BuiltInCategory.OST_StructuralColumns。</p>
<p>代码区域29-2：使用BuiltInCategory.OST_StructuralFraming</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">GetBeamAndColumnSymbols</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    List&lt;FamilySymbol&gt; columnTypes = <span class="keyword">new</span> List&lt;FamilySymbol&gt;();</span><br><span class="line">    List&lt;FamilySymbol&gt; framingTypes = <span class="keyword">new</span> List&lt;FamilySymbol&gt;();</span><br><span class="line">    FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">    ICollection&lt;Element&gt; elements = collector.OfClass(<span class="keyword">typeof</span>(Family)).ToElements();</span><br><span class="line"></span><br><span class="line">    <span class="keyword">foreach</span>(Element element <span class="keyword">in</span> elements)</span><br><span class="line">    &#123;</span><br><span class="line">        Family family = element <span class="keyword">as</span> Family;</span><br><span class="line">        Category category = family.FamilyCategory;</span><br><span class="line">        <span class="keyword">if</span> (<span class="literal">null</span> != category)</span><br><span class="line">        &#123;</span><br><span class="line">            ISet&lt;ElementId&gt; familySymbolIds = family.GetFamilySymbolIds();</span><br><span class="line">            <span class="keyword">if</span> ((<span class="built_in">int</span>)BuiltInCategory.OST_StructuralColumns == category.Id.IntegerValue)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> familySymbolIds)</span><br><span class="line">                &#123;</span><br><span class="line">                    FamilySymbol symbol = family.Document.GetElement(id) <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">                    columnTypes.Add(symbol);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">else</span> <span class="keyword">if</span> ((<span class="built_in">int</span>)BuiltInCategory.OST_StructuralFraming == category.Id.IntegerValue)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">foreach</span> (ElementId id <span class="keyword">in</span> familySymbolIds)</span><br><span class="line">                &#123;</span><br><span class="line">                    FamilySymbol symbol = family.Document.GetElement(id) <span class="keyword">as</span> FamilySymbol;</span><br><span class="line">                    framingTypes.Add(symbol);</span><br><span class="line">                &#125;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="built_in">string</span> message = <span class="string">&quot;Column Types: &quot;</span>;</span><br><span class="line">    <span class="keyword">foreach</span> (FamilySymbol familySymbol <span class="keyword">in</span> columnTypes)</span><br><span class="line">    &#123;</span><br><span class="line">        message += <span class="string">&quot;\n&quot;</span> + familySymbol.Name;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    TaskDialog.Show(<span class="string">&quot;Revit&quot;</span>,message);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>可以使用FamilyInstance.ExtensionUtility属性获取和设置梁缩进属性。如果此属性返回null，则无法修改梁缩进。</p>
<p><strong>BeamSystem</strong></p>
<p>BeamSystem提供对梁系统的完全访问和编辑能力。可以获取和设置其所有属性，例如BeamSystemType、BeamType、Direction和Level。方向不限于一条边。它可以设置为与BeamSystem在同一平面上的任何XYZ坐标。</p>
<p>注意：在UI中或通过API更改了Elevation属性后，不能更改StructuralBeam AnalyticalModel。在下图中，梁系统高程更改为10英尺后，分析模型线仍保留在原始位置。</p>
<p><img src="https://help.autodesk.com/cloudhelp/2018/CHS/Revit-API/images/GUID-1A4BF557-4296-4FE8-BCA3-CD3E1520BA7A.png"></p>
<p>图156：改变梁系统标高</p>
<h3 id="桁架"><a href="#桁架" class="headerlink" title="桁架"></a>桁架</h3><p><strong>桁架</strong></p>
<p>桁架类表示Revit中的所有桁架类型。TrussType属性指示桁架的类型。</p>
<p>代码区域29-7：在两个柱上创建桁架</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">Truss <span class="title">CreateTruss</span>(<span class="params">Autodesk.Revit.DB.Document document, FamilyInstance column1, FamilyInstance column2</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    Truss truss = <span class="literal">null</span>;</span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document, <span class="string">&quot;Add Truss&quot;</span>))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="keyword">if</span> (transaction.Start() == TransactionStatus.Started)</span><br><span class="line">        &#123;</span><br><span class="line">            <span class="comment">//sketchPlane</span></span><br><span class="line">            XYZ origin = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ xDirection = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ yDirection = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">1</span>, <span class="number">0</span>);</span><br><span class="line">            XYZ zDirection = <span class="keyword">new</span> XYZ(<span class="number">0</span>, <span class="number">0</span>, <span class="number">1</span>);</span><br><span class="line">            Plane plane = Plane.Create(<span class="keyword">new</span> Frame(origin, xDirection, yDirection, zDirection));</span><br><span class="line">            SketchPlane sketchPlane = SketchPlane.Create (document, plane);</span><br><span class="line"></span><br><span class="line">            <span class="comment">//new base Line - use line that spans two selected columns</span></span><br><span class="line">            AnalyticalModel frame1 = column1.GetAnalyticalModel() <span class="keyword">as</span> AnalyticalModel;</span><br><span class="line">            XYZ centerPoint1 = (frame1.GetCurve() <span class="keyword">as</span> Line).GetEndPoint(<span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">            AnalyticalModel frame2 = column2.GetAnalyticalModel() <span class="keyword">as</span> AnalyticalModel;</span><br><span class="line">            XYZ centerPoint2 = (frame2.GetCurve() <span class="keyword">as</span> Line).GetEndPoint(<span class="number">0</span>);</span><br><span class="line"></span><br><span class="line">            XYZ startPoint = <span class="keyword">new</span> XYZ(centerPoint1.X, centerPoint1.Y, <span class="number">0</span>);</span><br><span class="line">            XYZ endPoint = <span class="keyword">new</span> XYZ(centerPoint2.X, centerPoint2.Y, <span class="number">0</span>);</span><br><span class="line">            Autodesk.Revit.DB.Line baseLine = <span class="literal">null</span>;</span><br><span class="line"></span><br><span class="line">            <span class="keyword">try</span></span><br><span class="line">            &#123;</span><br><span class="line">                baseLine = Line.CreateBound(startPoint, endPoint);</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">catch</span> (System.ArgumentException)</span><br><span class="line">            &#123;</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;Selected columns are too close to create truss.&quot;</span>);</span><br><span class="line">            &#125;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// use the active view for where the truss&#x27;s tag will be placed; View used in</span></span><br><span class="line">            <span class="comment">// NewTruss should be plan or elevation view parallel to the truss&#x27;s base line </span></span><br><span class="line">            Autodesk.Revit.DB.View view = document.ActiveView;</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Get a truss type for the truss</span></span><br><span class="line">            FilteredElementCollector collector = <span class="keyword">new</span> FilteredElementCollector(document);</span><br><span class="line">            collector.OfClass(<span class="keyword">typeof</span>(FamilySymbol));</span><br><span class="line">            collector.OfCategory(BuiltInCategory.OST_Truss);</span><br><span class="line"></span><br><span class="line">            TrussType trussType = collector.FirstElement() <span class="keyword">as</span> TrussType;</span><br><span class="line"></span><br><span class="line">            <span class="keyword">if</span> (<span class="literal">null</span> != trussType)</span><br><span class="line">            &#123;</span><br><span class="line">                truss = Truss.Create(document, trussType.Id, sketchPlane.Id, baseLine);</span><br><span class="line">                transaction.Commit();</span><br><span class="line">            &#125;</span><br><span class="line">            <span class="keyword">else</span></span><br><span class="line">            &#123;</span><br><span class="line">                transaction.RollBack();</span><br><span class="line">                <span class="keyword">throw</span> <span class="keyword">new</span> Exception(<span class="string">&quot;No truss types found in document.&quot;</span>);</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">            </span><br><span class="line">    <span class="keyword">return</span> truss;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="加强"><a href="#加强" class="headerlink" title="加强"></a>加强</h3><p>Revit API提供了用于管理有效主体（如混凝土柱、梁、墙、基础和结构楼板）中的钢筋（如钢筋、钢筋或钢筋网）的类。</p>
<p>本节中的主题</p>
<ul>
<li>Rebar 钢筋<br>Rebar类表示用于加强适当元素（如混凝土梁、柱、板或基础）的钢筋。</li>
<li>钢筋连接器<br>钢筋连接器用于连接相邻钢筋。</li>
<li>区域和路径钢筋<br>Revit API提供了表示Revit结构要素中的面积钢筋和路径钢筋的类。</li>
<li>织物增强<br>钢筋网是一层由焊接钢丝网制成的钢筋网，并置于混凝土板或墙内。</li>
<li>钢筋容器<br>钢筋容器是表示一个主体中钢筋聚合的元素。此元素只能通过API创建。</li>
<li>钢筋设置<br>有关模型中钢筋的几个设置在文档级别进行控制，并通过文档的ReinfocementSettings类进行访问。</li>
<li>钢筋舍入<br>钢筋修圆是编制施工图的重要内容。钢筋长度公差小于行业或当地标准通常被视为不适用于指定钢筋。</li>
</ul>
<h4 id="钢筋"><a href="#钢筋" class="headerlink" title="钢筋"></a>钢筋</h4><p>Rebar 类表示用于加固合适元素（如混凝土梁、柱、板或基础）的钢筋。</p>
<p> <strong>创建钢筋</strong></p>
<p>您可以使用以下三种静态 Rebar 方法之一创建钢筋对象。</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="keyword">static</span> Rebar Rebar.CreateFromCurves(</span><br><span class="line">        Document doc,</span><br><span class="line">        RebarStyle style,</span><br><span class="line">        RebarBarType rebarType,</span><br><span class="line">        RebarHookType startHook,</span><br><span class="line">        RebarHookType endHook,</span><br><span class="line">        Element host,</span><br><span class="line">        XYZ norm,</span><br><span class="line">        IList&lt;Curve&gt; curves,</span><br><span class="line">        RebarHookOrientation startHookOrient,</span><br><span class="line">        RebarHookOrientation endHookOrient,</span><br><span class="line">        <span class="built_in">bool</span> useExistingShapeIfPossible,</span><br><span class="line">        <span class="built_in">bool</span> createNewShape</span><br><span class="line">);<span class="comment">//在项目中创建 Rebar 元素的新实例。所有曲线都必须属于由法线和原点定义的平面。</span></span><br></pre></td></tr></table></figure>

<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="keyword">static</span> Rebar Rebar.CreateFromRebarShape(</span><br><span class="line">        Document doc,</span><br><span class="line">        RebarShape rebarShape,</span><br><span class="line">        RebarBarType rebarType,</span><br><span class="line">        Element host,</span><br><span class="line">        XYZ origin,</span><br><span class="line">        XYZ xVec,</span><br><span class="line">        XYZ yVec</span><br><span class="line">);<span class="comment">//创建一个新的 Rebar 作为 RebarShape 的实例。该实例将具有 RebarShape 中的默认形状参数，其位置基于形状定义中形状的边界框。在计算形状的边界框之前，将从形状中删除钩子。如果在文档中可以找到合适的钩子，它们将被任意分配。</span></span><br></pre></td></tr></table></figure>

<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="keyword">static</span> Rebar Rebar.CreateFromCurvesAndShape(</span><br><span class="line">        Document doc,</span><br><span class="line">        RebarShape rebarShape,</span><br><span class="line">        RebarBarType rebarType,</span><br><span class="line">        RebarHookType startHook,</span><br><span class="line">        RebarHookType endHook,  </span><br><span class="line">        Element host,</span><br><span class="line">        XYZ norm,</span><br><span class="line">        IList&lt;Curve&gt; curves,</span><br><span class="line">        RebarHookOrientation startHookOrient,</span><br><span class="line">        RebarHookOrientation endHookOrient</span><br><span class="line">);<span class="comment">//在项目中创建 Rebar 元素的新实例。该实例将具有 RebarShape 中的默认形状参数。所有曲线都必须属于由法线和原点定义的平面。</span></span><br></pre></td></tr></table></figure>

<p>第一个版本从描述钢筋的曲线数组创建钢筋，而第二个版本根据 RebarShape 和位置创建 Rebar 对象。第三个版本从曲线数组中基于 RebarShape 创建钢筋。</p>
<p>使用 CreateFromCurves（） 或 CreateFromCurvesAndShape（） 方法时，参数 RebarBarType 和 RebarHookType 在文档的 RebarBarTypes 和 RebarHookTypes 属性中可用。</p>
<p>以下代码说明了如何创建具有特定布局的 Rebar。</p>
<p>代码区域 29-8：创建具有特定布局的钢筋</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="function">Rebar <span class="title">CreateRebar</span>(<span class="params">Autodesk.Revit.DB.Document document, FamilyInstance column, RebarBarType barType, RebarHookType hookType</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Define the rebar geometry information - Line rebar</span></span><br><span class="line">    LocationPoint location = column.Location <span class="keyword">as</span> LocationPoint;</span><br><span class="line">    XYZ origin = location.Point;</span><br><span class="line">    XYZ normal = <span class="keyword">new</span> XYZ(<span class="number">1</span>, <span class="number">0</span>, <span class="number">0</span>);</span><br><span class="line">    <span class="comment">// create rebar 9&#x27; long</span></span><br><span class="line">    XYZ rebarLineEnd = <span class="keyword">new</span> XYZ(origin.X, origin.Y, origin.Z + <span class="number">9</span>);</span><br><span class="line">    Line rebarLine = Line.CreateBound(origin, rebarLineEnd);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Create the line rebar</span></span><br><span class="line">    IList&lt;Curve&gt; curves = <span class="keyword">new</span> List&lt;Curve&gt;();</span><br><span class="line">    curves.Add(rebarLine);</span><br><span class="line"></span><br><span class="line">    Rebar rebar = Rebar.CreateFromCurves(document, Autodesk.Revit.DB.Structure.RebarStyle.Standard, barType, hookType, hookType,</span><br><span class="line">                        column, origin, curves, RebarHookOrientation.Right, RebarHookOrientation.Left, <span class="literal">true</span>, <span class="literal">true</span>);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">if</span> (<span class="literal">null</span> != rebar)</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// set specific layout for new rebar as fixed number, with 10 bars, distribution path length of 1.5&#x27;</span></span><br><span class="line">        <span class="comment">// with bars of the bar set on the same side of the rebar plane as indicated by normal</span></span><br><span class="line">        <span class="comment">// and both first and last bar in the set are shown</span></span><br><span class="line">        rebar.GetShapeDrivenAccessor().SetLayoutAsFixedNumber(<span class="number">10</span>, <span class="number">1.5</span>, <span class="literal">true</span>, <span class="literal">true</span>, <span class="literal">true</span>);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">return</span> rebar;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p><strong>注意：</strong>有关创建钢筋元素的更多示例，请参见 Revit SDK 附带的钢筋和 NewRebar 示例应用程序。</p>
<p>下表列出了 Parameter REBAR_ELEM_LAYOUT_RULE的整数值：</p>
<p>表 59：钢筋布局规则</p>
<table>
<thead>
<tr>
<th><strong>Value 值</strong></th>
<th><strong>0</strong></th>
<th><strong>1</strong></th>
<th><strong>2</strong></th>
<th><strong>3</strong></th>
<th><strong>4</strong></th>
</tr>
</thead>
<tbody><tr>
<td>描述</td>
<td>None</td>
<td>固定数量</td>
<td>最大间距</td>
<td>带间距的数字</td>
<td>最小净间距</td>
</tr>
</tbody></table>
<p>The Rebar.GetShapeDrivenAccessor().ScaleToBox（） 方法提供了一种同时设置所有形状参数的方法。该行为类似于放置 Rebar 的 UI。</p>
<p><strong>RebarHostData 和 RebarCoverType</strong></p>
<p>明确保护层与有效钢筋主体的各个面关联。可以通过Autodesk.Revit.Elements.RebarHostData对象访问主体的保护层设置。通过参数提供了一种更简单、功能更弱的访问相同设置的机制。</p>
<p>Cover 由命名为偏移的距离定义，建模为 Autodesk.Revit.DB.Structure.RebarCoverType 的元素。</p>
<p><strong>编号</strong></p>
<p>钢筋是可以通过Revit API控制其编号的元素类别之一。NumberingSchema和NumberingSchemaType类可用于定义钢筋元素的组织方式，以便对其进行编号&#x2F;标记。每个NumberingSchema控制一种特定类型的元素的编号。NumberingSchema的元素也是元素，并且每个Revit文档中的每种类型始终只有一个。所有内置编号架构的可用类型都在NumberingSchemaTypes类中枚举。</p>
<p>属于特定模式（例如NumberingSchemaTypes.StructuralNumberingSchemas.Rebar）的元素（例如Rebar）按顺序组织和编号。序列是共享相同编号分区的元素的集合，编号分区由它们各自的分区参数（NUMBER_PARTITION_PARAM）值定义。编号序列必须至少包含一个元素。换句话说，一旦存在至少一个元素，其分区参数具有不同于其他元素（在相同的编号模式中）的值，则建立序列。如果最后一个元素被删除（删除或移动到不同的序列），那么空序列将不再存在。</p>
<p>元素在创建时（基于当时的编号分区值）被分配给序列，方法是显式修改元素的Partition参数或使用AssignElementsToSequence（）方法。AssignElementsToSequence（）方法优于显式更改Partition参数，因为该方法会立即将更改应用于序列和元素编号，而更改的参数仅在当前事务关闭后生效。</p>
<p>除了直接或间接更改元素的Partition参数外，还可以使用NumberingSchema类的方法重新组织编号序列。MoveSequence（）方法将现有序列的所有元素移动到架构中尚不存在的新序列，从而有效地重命名所有受影响元素上的Partition参数。方法的作用是：在应用匹配策略的同时，从一个序列中删除所有元素，并将它们追加到另一个现有序列的元素中。方法MergeSequences（）接受所有指定序列的元素，并将它们全部移动到新创建的序列中。所有合并的元素将重新编号，并根据需要根据匹配算法进行匹配。</p>
<p>下面的示例使用MoveSequence（）方法在两个编号序列中交换Rebar的编号。</p>
<p>代码区域：交换号码</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"><span class="doctag">///</span> <span class="doctag">&lt;summary&gt;</span></span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> This method uses multiple moving operations to swap numbers</span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> for Rebars in two numbering sequences. The sequences are</span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> identified by the names of two numbering partitions.</span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> <span class="doctag">&lt;/summary&gt;</span></span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> <span class="doctag">&lt;param name=&quot;document&quot;&gt;</span>Document to modify<span class="doctag">&lt;/param&gt;</span></span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> <span class="doctag">&lt;param name=&quot;part1&quot;&gt;</span>Name of the partition of one numbering sequence<span class="doctag">&lt;/param&gt;</span></span></span><br><span class="line"><span class="comment"><span class="doctag">///</span> <span class="doctag">&lt;param name=&quot;part2&quot;&gt;</span>Name of the partition of another numbering sequence<span class="doctag">&lt;/param&gt;</span></span></span><br><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">SwapNumberingSequences</span>(<span class="params">Document document, <span class="built_in">string</span> part1, <span class="built_in">string</span> part2</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Obtain a schema object for a particular kind of elements </span></span><br><span class="line">    NumberingSchema schema = NumberingSchema.GetNumberingSchema(document,NumberingSchemaTypes.StructuralNumberingSchemas.Rebar);</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Changes to numbering sequences must be made inside a transaction</span></span><br><span class="line">        transaction.Start(<span class="string">&quot;Swap Numbering Sequences&quot;</span>);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// We will use a temporary partition for the swap operation,</span></span><br><span class="line">        <span class="comment">// for the move operation only works if the target partition </span></span><br><span class="line">        <span class="comment">// does not exist yet in the same numbering schema.</span></span><br><span class="line">        <span class="comment">// (We assume this TEMPORARY partition does not exist.)</span></span><br><span class="line">        <span class="built_in">string</span> tempPartition = <span class="string">&quot;TEMPORARY&quot;</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Step 1</span></span><br><span class="line">        <span class="comment">// First we move all elements from one sequence into </span></span><br><span class="line">        <span class="comment">// a partition we know does not exist. This action will</span></span><br><span class="line">        <span class="comment">// create the temporary partition and remove the original</span></span><br><span class="line">        <span class="comment">// one (part1).</span></span><br><span class="line">        schema.MoveSequence(part1, tempPartition);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Step 2</span></span><br><span class="line">        <span class="comment">// With the sequence in partition &#x27;part1&#x27; removed</span></span><br><span class="line">        <span class="comment">// we can now move elements from the second sequence to it.</span></span><br><span class="line">        <span class="comment">// This action will re-create a sequence in partition &#x27;part1&#x27;</span></span><br><span class="line">        <span class="comment">// and remove the sequence in partition &#x27;part2&#x27;</span></span><br><span class="line">        schema.MoveSequence(part2, part1);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Step 3</span></span><br><span class="line">        <span class="comment">// Finally, we can move elements &#x27;parked&#x27; in the temporary</span></span><br><span class="line">        <span class="comment">// sequence to partition &#x27;part2&#x27;, for that partition was</span></span><br><span class="line">        <span class="comment">// removed in the previous step and thus can now be created</span></span><br><span class="line">        <span class="comment">// again. The temporary partition will be automatically </span></span><br><span class="line">        <span class="comment">// removed upon completing this step.</span></span><br><span class="line">        schema.MoveSequence(tempPartition, part2);</span><br><span class="line"></span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>不同序列中的元素独立地编号，这意味着即使元素不同，在两个序列中也可能存在具有相同编号的元素。同样，在两个或更多个序列中可能存在完全相同的元素，其具有不同的数字。然而，在每个编号序列内，任何两个相同的元素将总是具有相同的编号，而不同的元件在编号序列内将永远不具有相同的编号。</p>
<p>创建后，Escape元素始终自动编号。每个新元素将获得一个递增的更大的数字。但是，与同一序列中的现有元素匹配的新元素将被分配相同的编号。元素将尽可能长时间地保留其分配的编号。这意味着，例如，如果删除了以前创建的某些钢筋图元，则所有剩余图元（在相同编号序列中）将保留其编号，这可能会导致相应编号序列中出现间隙。对于不需要空位的序列，可以通过调用RemoveGaps（）来移除空位。</p>
<p>下面的示例通过删除编号序列中的任何剩余间隙并设置每个序列的起始编号以使序列中的编号不重叠来合并钢筋元素上的编号。</p>
<p>代码区域：Consolidate Rebar Numbers</p>
<figure class="highlight c#"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> <span class="keyword">void</span> <span class="title">ConsolidateRebarNumbers</span>(<span class="params">Document document</span>)</span></span><br><span class="line">&#123;</span><br><span class="line">    <span class="comment">// Obtain a schema object for a particular kind of elements </span></span><br><span class="line">    NumberingSchema schema = NumberingSchema.GetNumberingSchema(document,NumberingSchemaTypes.StructuralNumberingSchemas.Rebar);</span><br><span class="line"></span><br><span class="line">    <span class="comment">// Collect the names of partitions of all the numbering sequences currently contained in the schema</span></span><br><span class="line">    IList&lt;<span class="built_in">string</span>&gt; sequences = schema.GetNumberingSequences();</span><br><span class="line"></span><br><span class="line">    <span class="keyword">using</span> (Transaction transaction = <span class="keyword">new</span> Transaction(document))</span><br><span class="line">    &#123;</span><br><span class="line">        <span class="comment">// Changes to numbers must be made inside a transaction</span></span><br><span class="line">        transaction.Start(<span class="string">&quot;Consolidate Rebar Numbers&quot;</span>);</span><br><span class="line"></span><br><span class="line">        <span class="comment">// First we make sure numbers in all sequences are consecutive</span></span><br><span class="line">        <span class="comment">// by removing possible gaps in numbers. Note: RemoveGaps does</span></span><br><span class="line">        <span class="comment">// nothing for a sequence where there are no gaps present.</span></span><br><span class="line"></span><br><span class="line">        <span class="comment">// We also want to find what the maximum range of numbers is</span></span><br><span class="line">        <span class="comment">// of all the sequences (the one the widest span of used numbers)</span></span><br><span class="line">        <span class="built_in">int</span> maxRange = <span class="number">0</span>;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">foreach</span> (<span class="built_in">string</span> name <span class="keyword">in</span> sequences)</span><br><span class="line">        &#123;</span><br><span class="line">            schema.RemoveGaps(name);</span><br><span class="line"></span><br><span class="line">            <span class="comment">// Here we use First() from the Linq extension.</span></span><br><span class="line">            <span class="comment">// There is always at least one range in every sequence,</span></span><br><span class="line">            <span class="comment">// and after gaps are closed there is exactly one range.</span></span><br><span class="line">            IntegerRange range = schema.GetNumbers(name).First();  </span><br><span class="line">            <span class="built_in">int</span> rangeSpan = <span class="number">1</span> + (range.High - range.Low);</span><br><span class="line">            <span class="keyword">if</span> (rangeSpan &gt; maxRange)</span><br><span class="line">            &#123;</span><br><span class="line">                maxRange = rangeSpan;</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// Next we give sequences different start numbers</span></span><br><span class="line">        <span class="comment">// starting with 100 and then stepping by at least</span></span><br><span class="line">        <span class="comment">// the maximum range we found in the previous step</span></span><br><span class="line">        <span class="built_in">int</span> startNumber = <span class="number">100</span>;</span><br><span class="line"></span><br><span class="line">        <span class="comment">// We round the range up to the closest 100</span></span><br><span class="line">        <span class="built_in">int</span> step = <span class="number">100</span> * (<span class="built_in">int</span>)((maxRange + <span class="number">99</span>) / <span class="number">100.0</span>);</span><br><span class="line"></span><br><span class="line">        <span class="keyword">foreach</span> (<span class="built_in">string</span> name <span class="keyword">in</span> sequences)</span><br><span class="line">        &#123;</span><br><span class="line">            schema.ShiftNumbers(name, startNumber);</span><br><span class="line">            startNumber += step;</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        transaction.Commit();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>数字被存储为每个编号元素上的编号参数的值。通过查询NumberingSchema.NumberingParameterId属性获取参数的ID。可以通过查询相应编号元素的参数来获得编号的值。该值是只读的，因此无法设置;它始终根据编号分区中元素的关系以及每个元素编号顺序中的匹配策略计算。</p>
<p>尽管编号总是自动分配给模式的所有元素，但ChangeNumber（）方法为程序员提供了一种方法，只要新编号在编号序列中是唯一的，就可以显式地覆盖特定编号。调用者指定一个要更改的数字和一个要应用的新值，前提是该值在同一编号序列中还不存在。</p>
<p><strong>分布类型</strong></p>
<p>Rebar.DistributionType属性可用于修改钢筋集的类型。钢筋集可以是“均匀”或“可变长度”，对于均匀分布类型：所有钢筋参数与集中的第一个钢筋相同。对于可变长度分布类型：考虑到集合中第一个钢筋的约束，钢筋参数可以变化（主要是长度）。</p>
<p>Rebar.GetParameterValueAtIndex() 方法的作用是：获取位于指定索引处的条形图的参数值。仅接受0和NumberOfBarPositions-1之间的值。如果DistributionType为Uniform，则无论索引如何，返回的ParameterValue都相同。如果DistributionType为VaryingLength，则返回的ParameterValue在给定索引处计算。</p>
</article><div class="tag_share"><div class="post-meta__tag-list"><a class="post-meta__tags" href="/tags/Revit%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E6%8C%87%E5%8D%97/">Revit二次开发人员指南</a></div><div class="post-share"><div class="social-share" data-image="/images/4stars.png" data-sites="facebook,twitter,wechat,weibo,qq"></div><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/css/share.min.css" media="print" onload="this.media='all'"><script src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/sharejs/dist/js/social-share.min.js" defer></script></div></div><nav class="pagination-post" id="pagination"><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/24%E5%AD%90%E5%85%83%E7%B4%A0/" title="24子元素"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info"><div class="info-1"><div class="info-item-1">上一篇</div><div class="info-item-2">24子元素</div></div><div class="info-2"><div class="info-item-1">子元素多个Revit图元现在可以包含称为子图元的细分。子元素提供了一种方法，使元素的各个部分的行为就像它们是真实的元素一样，而不会产生向模型中添加更多完整元素的开销。 许多Revit功能（例如，参数、明细表和标记）都设计用于对图元进行操作。因此，Revit代码需要将对象表示为元素，以便它们参与这些功能。这可能会导致可伸缩性问题，因为每个元素都会增加开销，并且添加许多元素可能会降低模型的性能。 另一种方法是使用子元素。图元可以显示其包含的一组“子图元”，指定其类别和参数等特征，并且某些Revit功能会将这些子图元视为普通图元。例如，子元素可以为主元素提供几何图形，并且可以独立于其父元素进行选择。它可能会有自己的（可设置的）类型以及分配的类别，该类别可以与其父元素不同。 在API中，新的Subelement类用于引用一个Element或给定Element的特定子元素。它通常与对元素或特定子元素的引用直接相关。 注：翻译自Revit API Developers Guide</div></div></div></a><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/28%E5%8F%AF%E6%89%A9%E5%B1%95%E5%82%A8%E5%AD%98/" title="28可扩展储存"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-right"><div class="info-1"><div class="info-item-1">下一篇</div><div class="info-item-2">28可扩展储存</div></div><div class="info-2"><div class="info-item-1">在Revit模型中存储数据使用共享参数或可扩展存储在Revit模型中存储数据。 Revit API提供了两种在Revit模型中存储数据的方法。第一种是使用共享参数。通过Revit API，可以通过编程方式访问通过Revit UI提供的相同共享参数功能。如果共享参数被定义为可见，则用户可以在元素的属性窗口中查看这些参数。可以将共享参数指定给许多（但不是所有）类别的图元。有关详细信息，请参阅共享参数。 另一个选项是可扩展存储，它允许您创建自定义数据结构，然后将该数据的实例分配给模型中的元素。用户在Revit UI中永远看不到这些数据，但其他第三方应用程序可以通过Revit...</div></div></div></a></nav><div class="relatedPosts"><div class="headline"><i class="fas fa-thumbs-up fa-fw"></i><span>相关推荐</span></div><div class="relatedPosts-list"><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/01%E5%BC%80%E5%A7%8B/" title="01开始"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-28</div><div class="info-item-2">01开始</div></div><div class="info-2"><div class="info-item-1">开始Revit 平台 API 可通过与 Microsoft .NET Framework 4.5.2 或 4.6 兼容的任何语言（如 Visual C# 或 Visual Basic .NET （VB.NET））进行完全访问。Visual C# 和 VB.NET 通常用于开发 Revit 平台 API 应用程序。但是，本手册的重点是使用 Visual C# 开发应用程序。 欢迎使用 Revit Platform API所有基于 Autodesk Revit 的产品都是参数化建筑信息模型 （BIM） 工具。这样的工具可以看作是用于构建 3D 模型的 CAD 程序，而不是一组单独的图纸文件。Autodesk Revit 建模是通过柱、墙、门和窗等真实世界的元素完成的。用户可以创建模型的视图，包括平面图、剖面图和详图索引。所有这些视图都是直接从 3D 物理模型生成的，因此在一个视图中所做的更改将自动传播到所有其他视图。此过程几乎消除了在模型中进行更改时更新多个图纸和细节的需要。 Autodesk Revit API 旨在反映与程序的图形用户界面相同的用户交互范例。因此，了解 API...</div></div></div></a><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/32%E5%8A%A8%E6%80%81%E6%A8%A1%E5%9E%8B%E6%9B%B4%E6%96%B0/" title="32动态模型更新"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-28</div><div class="info-item-2">32动态模型更新</div></div><div class="info-2"><div class="info-item-1">动态模型更新动态模型更新为Revit API应用程序提供了修改Revit模型的能力，作为对模型中发生的更改（当这些更改即将在事务结束时提交时）的反应。Revit API应用程序可以通过实现IUpdater接口并将其注册到UpdaterRegistry类来创建更新程序。注册包括指定模型中的哪些更改应该触发更新程序。 Pages in this section 本节中的页面  实现IUpdater Execute方法 注册更新程序 Exposure to...</div></div></div></a><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/33%E5%91%BD%E4%BB%A4/" title="33命令"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-28</div><div class="info-item-2">33命令</div></div><div class="info-2"><div class="info-item-1">命令Revit API 提供对现有 Revit 命令的访问，这些命令位于选项卡、应用程序菜单或右键单击菜单中。使用 API 处理 Revit 命令的主要方法是替换现有命令实现或发布命令。 替代 Revit 命令AddInCommandBinding 类可用于替代 Revit 中的现有命令。它有三个与替换现有命令实现相关的事件。  BeforeExecuted - 此只读事件在关联命令执行之前发生。应用程序可以对此事件做出反应，但不能更改文档或影响命令的调用。 CanExecute - 当关联的命令启动检查以确定是否可以在命令目标上执行命令时出现。 Executed - 当执行关联的命令时，将发生此事件，并且应在此处执行任何覆盖实现。  要创建 commandbinding，请调用 UIApplication.CreateAddInCommandBinding（） 或 UIControlledApplication.CreateAddInCommandBinding（）。这两种方法都需要 RevitCommandId ID 来标识要替换的命令处理程序。RevitCommandId...</div></div></div></a><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/31%E5%8F%AF%E5%81%9C%E9%9D%A0%E5%AF%B9%E8%AF%9D%E6%A1%86%E7%AA%97%E6%A0%BC/" title="31可停靠对话框窗格"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-28</div><div class="info-item-2">31可停靠对话框窗格</div></div><div class="info-2"><div class="info-item-1">可停靠对话框窗格自Revit 2013以来，应用程序可以通过利用Revit API中的Idling事件（用户界面事件和外部事件）类来使用无模式对话框。需要非模态对话框的加载项也可以选择使用可停靠的非模态对话框。与标准的无模式对话框类似，可停靠对话框是注册的Windows Presentation...</div></div></div></a><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/30%E5%A4%96%E9%83%A8%E4%BA%8B%E4%BB%B6/" title="30外部事件"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-28</div><div class="info-item-2">30外部事件</div></div><div class="info-2"><div class="info-item-1">外部事件Revit API提供了一个外部事件框架，以适应非模态对话框的使用。它是为异步处理量身定制的，其操作类似于具有默认频率的Idling事件。 要使用外部事件框架实现无模式对话框，请执行以下步骤：  通过从IExternalEventException接口派生来实现外部事件处理程序 使用静态ExternalEvent.Create（）方法创建ExternalEvent 当需要执行Revit操作的无模式对话框中发生事件时，调用ExternalEvent.Raise（） 当存在可用的空闲时间周期时，Revit将调用IExternalEvents.Execute（）方法的实现。  IExternalEventHandler这是要为外部事件实现的接口。实现此接口的类的实例注册到Revit中，每次引发相应的外部事件时，都会调用此接口的Execute方法。 IExternalEventHandler...</div></div></div></a><a class="pagination-related" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/29%E4%BA%8B%E4%BB%B6/" title="29事件"><div class="cover" style="background: var(--default-bg-color)"></div><div class="info text-center"><div class="info-1"><div class="info-item-1"><i class="far fa-calendar-alt fa-fw"></i> 2024-12-28</div><div class="info-item-2">29事件</div></div><div class="info-2"><div class="info-item-1">...</div></div></div></a></div></div><hr class="custom-hr"/><div id="post-comment"><div class="comment-head"><div class="comment-headline"><i class="fas fa-comments fa-fw"></i><span> 评论</span></div></div><div class="comment-wrap"><div><div id="giscus-wrap"></div></div></div></div></div><div class="aside-content" id="aside-content"><div class="card-widget card-info text-center"><div class="avatar-img"><img src="/images/4stars.png" onerror="this.onerror=null;this.src='/img/friend_404.gif'" alt="avatar"/></div><div class="author-info-name">funtim41@gmail.com</div><div class="author-info-description">实践-认识-再实践-再认识</div><div class="site-data"><a href="/archives/"><div class="headline">文章</div><div class="length-num">32</div></a><a href="/tags/"><div class="headline">标签</div><div class="length-num">1</div></a><a href="/categories/"><div class="headline">分类</div><div class="length-num">1</div></a></div><a id="card-info-btn" target="_blank" rel="noopener" href="https://github.com/FunTim41"><i class="fab fa-github"></i><span>Follow Me</span></a><div class="card-info-social-icons"><a class="social-icon" href="https://github.com/FunTim41" target="_blank" title="Github"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></div></div><div class="card-widget card-announcement"><div class="item-headline"><i class="fas fa-bullhorn fa-shake"></i><span>公告</span></div><div class="announcement_content">This is my Blog</div></div><div class="sticky_layout"><div class="card-widget" id="card-toc"><div class="item-headline"><i class="fas fa-stream"></i><span>目录</span><span class="toc-percentage"></span></div><div class="toc-content"><ol class="toc"><li class="toc-item toc-level-1"><a class="toc-link" href="#%E7%BB%93%E6%9E%84%E5%B7%A5%E7%A8%8B"><span class="toc-number">1.</span> <span class="toc-text">结构工程</span></a><ol class="toc-child"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%BB%93%E6%9E%84%E6%A8%A1%E5%9E%8B%E5%85%83%E7%B4%A0"><span class="toc-number">1.1.</span> <span class="toc-text">结构模型元素</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%BB%93%E6%9E%84%E6%9F%B1%E3%80%81%E6%A2%81%E5%92%8C%E6%94%AF%E6%92%91"><span class="toc-number">1.1.1.</span> <span class="toc-text">结构柱、梁和支撑</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%A1%81%E6%9E%B6"><span class="toc-number">1.1.2.</span> <span class="toc-text">桁架</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%8A%A0%E5%BC%BA"><span class="toc-number">1.1.3.</span> <span class="toc-text">加强</span></a><ol class="toc-child"><li class="toc-item toc-level-4"><a class="toc-link" href="#%E9%92%A2%E7%AD%8B"><span class="toc-number">1.1.3.1.</span> <span class="toc-text">钢筋</span></a></li></ol></li></ol></li></ol></li></ol></div></div><div class="card-widget card-recent-post"><div class="item-headline"><i class="fas fa-history"></i><span>最新文章</span></div><div class="aside-list"><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/01%E5%BC%80%E5%A7%8B/" title="01开始">01开始</a><time datetime="2024-12-29T06:29:25.217Z" title="更新于 2024-12-29 14:29:25">2024-12-29</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/32%E5%8A%A8%E6%80%81%E6%A8%A1%E5%9E%8B%E6%9B%B4%E6%96%B0/" title="32动态模型更新">32动态模型更新</a><time datetime="2024-12-28T13:19:57.729Z" title="更新于 2024-12-28 21:19:57">2024-12-28</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/33%E5%91%BD%E4%BB%A4/" title="33命令">33命令</a><time datetime="2024-12-28T13:19:57.729Z" title="更新于 2024-12-28 21:19:57">2024-12-28</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/31%E5%8F%AF%E5%81%9C%E9%9D%A0%E5%AF%B9%E8%AF%9D%E6%A1%86%E7%AA%97%E6%A0%BC/" title="31可停靠对话框窗格">31可停靠对话框窗格</a><time datetime="2024-12-28T13:19:57.728Z" title="更新于 2024-12-28 21:19:57">2024-12-28</time></div></div><div class="aside-list-item no-cover"><div class="content"><a class="title" href="/2024/12/28/%E4%BA%8C%E5%BC%80%E6%8C%87%E5%8D%97/30%E5%A4%96%E9%83%A8%E4%BA%8B%E4%BB%B6/" title="30外部事件">30外部事件</a><time datetime="2024-12-28T13:19:57.727Z" title="更新于 2024-12-28 21:19:57">2024-12-28</time></div></div></div></div></div></div></main><footer id="footer" style="background-image: url(/images/topback.jpg);"><div id="footer-wrap"><div class="copyright">&copy;2024 By funtim41@gmail.com</div><div class="framework-info"><span>框架 </span><a target="_blank" rel="noopener" href="https://hexo.io">Hexo</a><span class="footer-separator">|</span><span>主题 </span><a target="_blank" rel="noopener" href="https://github.com/jerryc127/hexo-theme-butterfly">Butterfly</a></div><div class="footer_custom_text">学而不思则罔，思而不学则殆。</div></div></footer></div><div id="rightside"><div id="rightside-config-hide"><button id="readmode" type="button" title="阅读模式"><i class="fas fa-book-open"></i></button><button id="darkmode" type="button" title="日间和夜间模式切换"><i class="fas fa-adjust"></i></button><button id="hide-aside-btn" type="button" title="单栏和双栏切换"><i class="fas fa-arrows-alt-h"></i></button></div><div id="rightside-config-show"><button id="rightside-config" type="button" title="设置"><i class="fas fa-cog fa-spin"></i></button><button class="close" id="mobile-toc-button" type="button" title="目录"><i class="fas fa-list-ul"></i></button><a id="to_comment" href="#post-comment" title="前往评论"><i class="fas fa-comments"></i></a><button id="go-up" type="button" title="回到顶部"><span class="scroll-percent"></span><i class="fas fa-arrow-up"></i></button></div></div><div><script src="/js/utils.js"></script><script src="/js/main.js"></script><script src="https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js"></script><script>(() => {
  const panguFn = () => {
    if (typeof pangu === 'object') pangu.autoSpacingPage()
    else {
      btf.getScript('https://cdn.jsdelivr.net/npm/pangu/dist/browser/pangu.min.js')
        .then(() => {
          pangu.autoSpacingPage()
        })
    }
  }

  const panguInit = () => {
    if (false){
      GLOBAL_CONFIG_SITE.isPost && panguFn()
    } else {
      panguFn()
    }
  }

  btf.addGlobalFn('pjaxComplete', panguInit, 'pangu')
  document.addEventListener('DOMContentLoaded', panguInit)
})()</script><div class="js-pjax"><script>(() => {
  const isShuoshuo = GLOBAL_CONFIG_SITE.isShuoshuo
  const option = null

  const getGiscusTheme = theme => theme === 'dark' ? 'dark' : 'light'

  const createScriptElement = config => {
    const ele = document.createElement('script')
    Object.entries(config).forEach(([key, value]) => {
      ele.setAttribute(key, value)
    })
    return ele
  }

  const loadGiscus = (el = document, key) => {
    const mappingConfig = isShuoshuo
      ? { 'data-mapping': 'specific', 'data-term': key }
      : { 'data-mapping': (option && option['data-mapping']) || 'pathname' }

    const giscusConfig = {
      src: 'https://giscus.app/client.js',
      'data-repo': 'FunTim41/funtim41.github.io',
      'data-repo-id': 'R_kgDONjG8ww',
      'data-category-id': 'DIC_kwDONjG8w84Cllg2',
      'data-theme': getGiscusTheme(document.documentElement.getAttribute('data-theme')),
      'data-reactions-enabled': '1',
      crossorigin: 'anonymous',
      async: true,
      ...option,
      ...mappingConfig
    }

    const scriptElement = createScriptElement(giscusConfig)

    el.querySelector('#giscus-wrap').appendChild(scriptElement)

    if (isShuoshuo) {
      window.shuoshuoComment.destroyGiscus = () => {
        if (el.children.length) {
          el.innerHTML = ''
          el.classList.add('no-comment')
        }
      }
    }
  }

  const changeGiscusTheme = theme => {
    const iframe = document.querySelector('#giscus-wrap iframe')
    if (iframe) {
      const message = {
        giscus: {
          setConfig: {
            theme: getGiscusTheme(theme)
          }
        }
      }
      iframe.contentWindow.postMessage(message, 'https://giscus.app')
    }
  }

  btf.addGlobalFn('themeChange', changeGiscusTheme, 'giscus')

  if (isShuoshuo) {
    'Giscus' === 'Giscus'
      ? window.shuoshuoComment = { loadComment: loadGiscus }
      : window.loadOtherComment = loadGiscus
    return
  }

  if ('Giscus' === 'Giscus' || !false) {
    if (false) btf.loadComment(document.getElementById('giscus-wrap'), loadGiscus)
    else loadGiscus()
  } else {
    window.loadOtherComment = loadGiscus
  }
})()</script></div><script defer="defer" id="fluttering_ribbon" mobile="false" src="https://cdn.jsdelivr.net/npm/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js"></script><script async data-pjax src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><div id="local-search"><div class="search-dialog"><nav class="search-nav"><span class="search-dialog-title">搜索</span><span id="loading-status"></span><button class="search-close-button"><i class="fas fa-times"></i></button></nav><div class="text-center" id="loading-database"><i class="fas fa-spinner fa-pulse"></i><span>  数据加载中</span></div><div class="search-wrap"><div id="local-search-input"><div class="local-search-box"><input class="local-search-box--input" placeholder="搜索文章" type="text"/></div></div><hr/><div id="local-search-results"></div><div id="local-search-stats-wrap"></div></div></div><div id="search-mask"></div><script src="/js/search/local-search.js"></script></div></div></body></html>